/** Shoulder girdle, shoulder, arm and forearm.
 *  reviewStatus is 'draft' throughout — see docs/anatomy-model.md §5. */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const UPPER_LIMB_MUSCLES: AnatomicalMuscle[] = [
  /* ---------------------------------------------------- scapular stabilizers */
  {
    id: 'trapezius', name: 'Trapezius', latin: 'Musculus trapezius',
    region: 'back', group: 'scapular stabilizers', palpable: true,
    origin: [at('external_occipital_protuberance'), at('nuchal_line_superior'),
             at('nuchal_ligament'), at('c7_t12_spinous')],
    insertion: [at('clavicle_lateral', 'upper fibres'), at('acromion', 'middle fibres'),
                at('scapular_spine', 'middle and lower fibres')],
    innervation: [inn('accessory', ['CN XI'], 'motor'),
                  inn('cervical_rami', ['C3', 'C4'], 'proprioceptive')],
    actions: [
      act('scapulothoracic', 'elevation', 'prime', 'upper fibres'),
      act('scapulothoracic', 'retraction', 'prime', 'middle fibres'),
      act('scapulothoracic', 'depression', 'prime', 'lower fibres'),
      act('scapulothoracic', 'upward_rotation', 'prime', 'upper and lower fibres together'),
      act('cervical_spine_joint', 'extension', 'assist'),
    ],
    heads: [
      { id: 'trapezius_upper', name: 'Upper trapezius', trainableUnitId: 'traps_upper',
        origin: [at('external_occipital_protuberance'), at('nuchal_ligament')],
        insertion: [at('clavicle_lateral')] },
      { id: 'trapezius_middle', name: 'Middle trapezius', trainableUnitId: 'traps_mid',
        origin: [at('c7_t12_spinous', 'C7–T3')], insertion: [at('acromion'), at('scapular_spine')] },
      { id: 'trapezius_lower', name: 'Lower trapezius', trainableUnitId: 'traps_lower',
        origin: [at('c7_t12_spinous', 'T4–T12')], insertion: [at('scapular_spine', 'medial end')] },
    ],
    reviewStatus: 'draft',
  },
  {
    id: 'levator_scapulae', name: 'Levator scapulae', latin: 'Musculus levator scapulae',
    region: 'back', group: 'scapular stabilizers', trainableUnitId: 'traps_upper',
    origin: [at('c1_c4_transverse')],
    insertion: [at('scapula_superior_angle'), at('scapula_medial_border', 'upper part')],
    innervation: [inn('dorsal_scapular', ['C5']), inn('cervical_rami', ['C3', 'C4'])],
    actions: [act('scapulothoracic', 'elevation'), act('scapulothoracic', 'downward_rotation'),
              act('cervical_spine_joint', 'lateral_flexion', 'assist', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'rhomboid_major', name: 'Rhomboid major', latin: 'Musculus rhomboideus major',
    region: 'back', group: 'scapular stabilizers', trainableUnitId: 'rhomboids',
    origin: [at('t3_t6_spinous', 'T2–T5')],
    insertion: [at('scapula_medial_border', 'below the root of the spine')],
    innervation: [inn('dorsal_scapular', ['C4', 'C5'])],
    actions: [act('scapulothoracic', 'retraction'), act('scapulothoracic', 'downward_rotation'),
              act('scapulothoracic', 'elevation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'rhomboid_minor', name: 'Rhomboid minor', latin: 'Musculus rhomboideus minor',
    region: 'back', group: 'scapular stabilizers', trainableUnitId: 'rhomboids',
    origin: [at('nuchal_ligament'), at('c2_c4_spinous', 'C7–T1')],
    insertion: [at('scapula_medial_border', 'at the root of the spine')],
    innervation: [inn('dorsal_scapular', ['C4', 'C5'])],
    actions: [act('scapulothoracic', 'retraction'), act('scapulothoracic', 'downward_rotation')],
    reviewStatus: 'draft',
  },
  {
    id: 'serratus_anterior', name: 'Serratus anterior', latin: 'Musculus serratus anterior',
    region: 'thorax', group: 'scapular stabilizers', trainableUnitId: 'traps_lower',
    palpable: true,
    origin: [at('ribs_1_8_lateral')],
    insertion: [at('scapula_medial_border', 'anterior/costal surface')],
    innervation: [inn('long_thoracic', ['C5', 'C6', 'C7'])],
    actions: [act('scapulothoracic', 'protraction'), act('scapulothoracic', 'upward_rotation')],
    notes: 'Long thoracic palsy produces winging of the scapula.',
    reviewStatus: 'draft',
  },
  {
    id: 'pectoralis_minor', name: 'Pectoralis minor', latin: 'Musculus pectoralis minor',
    region: 'thorax', group: 'scapular stabilizers', trainableUnitId: 'pec_lower',
    origin: [at('ribs_3_5')], insertion: [at('coracoid_process')],
    innervation: [inn('medial_pectoral', ['C8', 'T1'])],
    actions: [act('scapulothoracic', 'depression'), act('scapulothoracic', 'protraction'),
              act('scapulothoracic', 'downward_rotation')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------- glenohumeral */
  {
    id: 'deltoid', name: 'Deltoid', latin: 'Musculus deltoideus',
    region: 'shoulder', palpable: true,
    origin: [at('clavicle_lateral', 'anterior fibres'), at('acromion', 'middle fibres'),
             at('scapular_spine', 'posterior fibres')],
    insertion: [at('deltoid_tuberosity')],
    innervation: [inn('axillary', ['C5', 'C6'])],
    actions: [
      act('glenohumeral', 'abduction', 'prime', 'middle fibres, 15–90°'),
      act('glenohumeral', 'flexion', 'prime', 'anterior fibres'),
      act('glenohumeral', 'internal_rotation', 'assist', 'anterior fibres'),
      act('glenohumeral', 'horizontal_adduction', 'prime', 'anterior fibres'),
      act('glenohumeral', 'extension', 'prime', 'posterior fibres'),
      act('glenohumeral', 'external_rotation', 'assist', 'posterior fibres'),
      act('glenohumeral', 'horizontal_abduction', 'prime', 'posterior fibres'),
    ],
    heads: [
      { id: 'deltoid_anterior', name: 'Anterior deltoid', trainableUnitId: 'delt_front',
        origin: [at('clavicle_lateral')], insertion: [at('deltoid_tuberosity')] },
      { id: 'deltoid_middle', name: 'Middle deltoid', trainableUnitId: 'delt_lateral',
        origin: [at('acromion')], insertion: [at('deltoid_tuberosity')] },
      { id: 'deltoid_posterior', name: 'Posterior deltoid', trainableUnitId: 'delt_rear',
        origin: [at('scapular_spine')], insertion: [at('deltoid_tuberosity')] },
    ],
    reviewStatus: 'draft',
  },
  {
    id: 'supraspinatus', name: 'Supraspinatus', latin: 'Musculus supraspinatus',
    region: 'shoulder', group: 'rotator cuff', trainableUnitId: 'supraspinatus',
    origin: [at('supraspinous_fossa')],
    insertion: [at('greater_tubercle', 'superior facet')],
    innervation: [inn('suprascapular', ['C5', 'C6'])],
    actions: [act('glenohumeral', 'abduction', 'prime', 'initiates the first ~15°'),
              act('glenohumeral', 'flexion', 'stabilize')],
    notes: 'The most commonly torn cuff tendon; passes under the acromion.',
    reviewStatus: 'draft',
  },
  {
    id: 'infraspinatus', name: 'Infraspinatus', latin: 'Musculus infraspinatus',
    region: 'shoulder', group: 'rotator cuff', trainableUnitId: 'cuff_ext_rotators',
    origin: [at('infraspinous_fossa')],
    insertion: [at('greater_tubercle', 'middle facet')],
    innervation: [inn('suprascapular', ['C5', 'C6'])],
    actions: [act('glenohumeral', 'external_rotation'),
              act('glenohumeral', 'horizontal_abduction', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'teres_minor', name: 'Teres minor', latin: 'Musculus teres minor',
    region: 'shoulder', group: 'rotator cuff', trainableUnitId: 'cuff_ext_rotators',
    origin: [at('scapula_lateral_border', 'upper two-thirds')],
    insertion: [at('greater_tubercle', 'inferior facet')],
    innervation: [inn('axillary', ['C5', 'C6'])],
    actions: [act('glenohumeral', 'external_rotation'), act('glenohumeral', 'adduction', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'subscapularis', name: 'Subscapularis', latin: 'Musculus subscapularis',
    region: 'shoulder', group: 'rotator cuff', trainableUnitId: 'subscapularis',
    origin: [at('subscapular_fossa')], insertion: [at('lesser_tubercle')],
    innervation: [inn('upper_subscapular', ['C5', 'C6']), inn('lower_subscapular', ['C5', 'C6'])],
    actions: [act('glenohumeral', 'internal_rotation'), act('glenohumeral', 'adduction', 'assist')],
    notes: 'The only cuff muscle on the anterior surface of the scapula.',
    reviewStatus: 'draft',
  },
  {
    id: 'teres_major', name: 'Teres major', latin: 'Musculus teres major',
    region: 'shoulder', trainableUnitId: 'teres_major',
    origin: [at('scapula_inferior_angle'), at('scapula_lateral_border', 'lower third')],
    insertion: [at('intertubercular_groove_medial')],
    innervation: [inn('lower_subscapular', ['C5', 'C6'])],
    actions: [act('glenohumeral', 'adduction'), act('glenohumeral', 'internal_rotation'),
              act('glenohumeral', 'extension')],
    notes: 'Often called "lat\'s little helper" — same three actions, no spinal attachment.',
    reviewStatus: 'draft',
  },
  {
    id: 'latissimus_dorsi', name: 'Latissimus dorsi', latin: 'Musculus latissimus dorsi',
    region: 'back', trainableUnitId: 'lats', palpable: true,
    origin: [at('t7_l5_spinous'), at('thoracolumbar_fascia'), at('iliac_crest', 'posterior third'),
             at('ribs_lower', 'ribs 9–12'), at('scapula_inferior_angle', 'variable slip')],
    insertion: [at('intertubercular_groove_floor')],
    innervation: [inn('thoracodorsal', ['C6', 'C7', 'C8'])],
    actions: [act('glenohumeral', 'extension'), act('glenohumeral', 'adduction'),
              act('glenohumeral', 'internal_rotation'),
              act('spine', 'lateral_flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'pectoralis_major', name: 'Pectoralis major', latin: 'Musculus pectoralis major',
    region: 'thorax', palpable: true,
    origin: [at('clavicle_medial', 'clavicular head'), at('sternum_body', 'sternocostal head'),
             at('costal_cartilages', 'ribs 1–6'), at('external_oblique_aponeurosis', 'abdominal head')],
    insertion: [at('intertubercular_groove_lateral')],
    innervation: [inn('lateral_pectoral', ['C5', 'C6', 'C7'], 'chiefly the clavicular head'),
                  inn('medial_pectoral', ['C8', 'T1'], 'chiefly the sternocostal head')],
    actions: [
      act('glenohumeral', 'adduction'), act('glenohumeral', 'internal_rotation'),
      act('glenohumeral', 'horizontal_adduction'),
      act('glenohumeral', 'flexion', 'prime', 'clavicular head, to about 60°'),
      act('glenohumeral', 'extension', 'assist', 'sternocostal head, from a flexed position'),
    ],
    heads: [
      { id: 'pec_major_clavicular', name: 'Clavicular head', trainableUnitId: 'pec_upper',
        origin: [at('clavicle_medial')], insertion: [at('intertubercular_groove_lateral')],
        actions: [act('glenohumeral', 'flexion'), act('glenohumeral', 'horizontal_adduction')] },
      { id: 'pec_major_sternocostal', name: 'Sternocostal head', trainableUnitId: 'pec_mid',
        origin: [at('sternum_body'), at('costal_cartilages')],
        insertion: [at('intertubercular_groove_lateral')] },
      { id: 'pec_major_abdominal', name: 'Abdominal head', trainableUnitId: 'pec_lower',
        origin: [at('external_oblique_aponeurosis')],
        insertion: [at('intertubercular_groove_lateral')] },
    ],
    notes: 'The insertion is twisted, so the clavicular fibres attach lower than the abdominal ones.',
    reviewStatus: 'draft',
  },
  {
    id: 'coracobrachialis', name: 'Coracobrachialis', latin: 'Musculus coracobrachialis',
    region: 'arm', trainableUnitId: 'delt_front',
    origin: [at('coracoid_process')], insertion: [at('humerus_shaft_medial', 'middle third')],
    innervation: [inn('musculocutaneous', ['C5', 'C6', 'C7'])],
    actions: [act('glenohumeral', 'flexion', 'assist'), act('glenohumeral', 'adduction', 'assist')],
    notes: 'Pierced by the musculocutaneous nerve.',
    reviewStatus: 'draft',
  },

  /* ---------------------------------------------------------------- upper arm */
  {
    id: 'biceps_brachii', name: 'Biceps brachii', latin: 'Musculus biceps brachii',
    region: 'arm', palpable: true,
    origin: [at('supraglenoid_tubercle', 'long head'), at('coracoid_process', 'short head')],
    insertion: [at('radial_tuberosity'), at('palmar_aponeurosis', 'via the bicipital aponeurosis')],
    innervation: [inn('musculocutaneous', ['C5', 'C6'])],
    actions: [act('elbow', 'flexion'), act('radioulnar', 'supination'),
              act('glenohumeral', 'flexion', 'assist')],
    heads: [
      { id: 'biceps_long_head', name: 'Long head', trainableUnitId: 'biceps_long',
        origin: [at('supraglenoid_tubercle')], insertion: [at('radial_tuberosity')] },
      { id: 'biceps_short_head', name: 'Short head', trainableUnitId: 'biceps_short',
        origin: [at('coracoid_process')], insertion: [at('radial_tuberosity')] },
    ],
    notes: 'Strongest supinator of the forearm; supination is weaker with the elbow extended.',
    reviewStatus: 'draft',
  },
  {
    id: 'brachialis', name: 'Brachialis', latin: 'Musculus brachialis',
    region: 'arm', trainableUnitId: 'brachialis',
    origin: [at('humerus_shaft_anterior', 'distal half')],
    insertion: [at('ulna_coronoid', 'and the ulnar tuberosity')],
    innervation: [inn('musculocutaneous', ['C5', 'C6']),
                  inn('radial', ['C7'], 'small lateral portion')],
    actions: [act('elbow', 'flexion')],
    notes: 'The workhorse elbow flexor: it acts regardless of forearm rotation.',
    reviewStatus: 'draft',
  },
  {
    id: 'triceps_brachii', name: 'Triceps brachii', latin: 'Musculus triceps brachii',
    region: 'arm', palpable: true,
    origin: [at('infraglenoid_tubercle', 'long head'),
             at('humerus_shaft_posterior', 'lateral head, above the radial groove'),
             at('humerus_shaft_posterior', 'medial head, below the radial groove')],
    insertion: [at('olecranon')],
    innervation: [inn('radial', ['C6', 'C7', 'C8'])],
    actions: [act('elbow', 'extension'),
              act('glenohumeral', 'extension', 'assist', 'long head only'),
              act('glenohumeral', 'adduction', 'assist', 'long head only')],
    heads: [
      { id: 'triceps_long_head', name: 'Long head', trainableUnitId: 'triceps_long',
        origin: [at('infraglenoid_tubercle')], insertion: [at('olecranon')],
        actions: [act('elbow', 'extension'), act('glenohumeral', 'extension')] },
      { id: 'triceps_lateral_head', name: 'Lateral head', trainableUnitId: 'triceps_lateral',
        origin: [at('humerus_shaft_posterior')], insertion: [at('olecranon')] },
      { id: 'triceps_medial_head', name: 'Medial head', trainableUnitId: 'triceps_medial',
        origin: [at('humerus_shaft_posterior')], insertion: [at('olecranon')] },
    ],
    notes: 'Only the long head crosses the shoulder — which is why overhead position '
         + 'lengthens it and biases it in extensions.',
    reviewStatus: 'draft',
  },
  {
    id: 'anconeus', name: 'Anconeus', latin: 'Musculus anconeus',
    region: 'arm', trainableUnitId: 'triceps_lateral',
    origin: [at('lateral_epicondyle')], insertion: [at('olecranon'), at('ulna_shaft', 'proximal posterior')],
    innervation: [inn('radial', ['C7', 'C8'])],
    actions: [act('elbow', 'extension', 'assist')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------------ forearm */
  {
    id: 'brachioradialis', name: 'Brachioradialis', latin: 'Musculus brachioradialis',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'brachioradialis',
    palpable: true,
    origin: [at('lateral_supracondylar_ridge', 'proximal two-thirds')],
    insertion: [at('radius_styloid')],
    innervation: [inn('radial', ['C5', 'C6'])],
    actions: [act('elbow', 'flexion', 'prime', 'strongest in neutral forearm')],
    notes: 'Radial-innervated but an elbow flexor — the classic exception.',
    reviewStatus: 'draft',
  },
  {
    id: 'pronator_teres', name: 'Pronator teres', latin: 'Musculus pronator teres',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('medial_epicondyle'), at('ulna_coronoid')],
    insertion: [at('radius_shaft', 'lateral surface, mid-shaft')],
    innervation: [inn('median', ['C6', 'C7'])],
    actions: [act('radioulnar', 'pronation'), act('elbow', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'pronator_quadratus', name: 'Pronator quadratus', latin: 'Musculus pronator quadratus',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('ulna_shaft', 'distal anterior')], insertion: [at('radius_shaft', 'distal anterior')],
    innervation: [inn('anterior_interosseous', ['C7', 'C8'])],
    actions: [act('radioulnar', 'pronation')],
    reviewStatus: 'draft',
  },
  {
    id: 'supinator', name: 'Supinator', latin: 'Musculus supinator',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'forearm_extensors',
    origin: [at('lateral_epicondyle'), at('supinator_crest')],
    insertion: [at('radius_shaft', 'proximal third')],
    innervation: [inn('posterior_interosseous', ['C6', 'C7'])],
    actions: [act('radioulnar', 'supination')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_carpi_radialis', name: 'Flexor carpi radialis',
    latin: 'Musculus flexor carpi radialis',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('medial_epicondyle', 'common flexor origin')],
    insertion: [at('metacarpal_2_3_base')],
    innervation: [inn('median', ['C6', 'C7'])],
    actions: [act('wrist', 'flexion'), act('wrist', 'abduction', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_carpi_ulnaris', name: 'Flexor carpi ulnaris',
    latin: 'Musculus flexor carpi ulnaris',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('medial_epicondyle', 'common flexor origin'), at('olecranon'),
             at('ulna_shaft', 'posterior border')],
    insertion: [at('pisiform'), at('hamate'), at('metacarpal_5_base')],
    innervation: [inn('ulnar', ['C7', 'C8'])],
    actions: [act('wrist', 'flexion'), act('wrist', 'adduction')],
    reviewStatus: 'draft',
  },
  {
    id: 'palmaris_longus', name: 'Palmaris longus', latin: 'Musculus palmaris longus',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('medial_epicondyle', 'common flexor origin')],
    insertion: [at('palmar_aponeurosis')],
    innervation: [inn('median', ['C7', 'C8'])],
    actions: [act('wrist', 'flexion', 'assist')],
    notes: 'Absent in roughly 15% of people, often unilaterally.',
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_digitorum_superficialis', name: 'Flexor digitorum superficialis',
    latin: 'Musculus flexor digitorum superficialis',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('medial_epicondyle', 'common flexor origin'), at('ulna_coronoid'),
             at('radius_shaft', 'anterior oblique line')],
    insertion: [at('phalanges_middle', 'digits 2–5')],
    innervation: [inn('median', ['C7', 'C8', 'T1'])],
    actions: [act('fingers', 'flexion', 'prime', 'proximal interphalangeal joints'),
              act('wrist', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_digitorum_profundus', name: 'Flexor digitorum profundus',
    latin: 'Musculus flexor digitorum profundus',
    region: 'forearm', compartment: 'anterior forearm', trainableUnitId: 'forearm_flexors',
    origin: [at('ulna_shaft', 'proximal anteromedial'), at('interosseous_membrane_forearm')],
    insertion: [at('phalanges_distal_hand', 'digits 2–5')],
    innervation: [inn('anterior_interosseous', ['C8', 'T1'], 'digits 2–3'),
                  inn('ulnar', ['C8', 'T1'], 'digits 4–5')],
    actions: [act('fingers', 'flexion', 'prime', 'distal interphalangeal joints'),
              act('wrist', 'flexion', 'assist')],
    notes: 'The only muscle that flexes the DIP joints; split innervation is a classic exam point.',
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_carpi_radialis_longus', name: 'Extensor carpi radialis longus',
    latin: 'Musculus extensor carpi radialis longus',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'forearm_extensors',
    origin: [at('lateral_supracondylar_ridge')], insertion: [at('metacarpal_2_3_base', '2nd metacarpal')],
    innervation: [inn('radial', ['C6', 'C7'])],
    actions: [act('wrist', 'extension'), act('wrist', 'abduction')],
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_carpi_radialis_brevis', name: 'Extensor carpi radialis brevis',
    latin: 'Musculus extensor carpi radialis brevis',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'forearm_extensors',
    origin: [at('lateral_epicondyle', 'common extensor origin')],
    insertion: [at('metacarpal_2_3_base', '3rd metacarpal')],
    innervation: [inn('radial', ['C7', 'C8'])],
    actions: [act('wrist', 'extension')],
    notes: 'The tendon most implicated in lateral epicondylitis (tennis elbow).',
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_digitorum', name: 'Extensor digitorum', latin: 'Musculus extensor digitorum',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'forearm_extensors',
    origin: [at('lateral_epicondyle', 'common extensor origin')],
    insertion: [at('extensor_expansion', 'digits 2–5')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('fingers', 'extension'), act('wrist', 'extension', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_carpi_ulnaris', name: 'Extensor carpi ulnaris',
    latin: 'Musculus extensor carpi ulnaris',
    region: 'forearm', compartment: 'posterior forearm', trainableUnitId: 'forearm_extensors',
    origin: [at('lateral_epicondyle', 'common extensor origin'), at('ulna_shaft', 'posterior border')],
    insertion: [at('metacarpal_5_base')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('wrist', 'extension'), act('wrist', 'adduction')],
    reviewStatus: 'draft',
  },
]
