/** Hip, thigh and leg. reviewStatus is 'draft' throughout — see
 *  docs/anatomy-model.md §5. */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const LOWER_LIMB_MUSCLES: AnatomicalMuscle[] = [
  /* ---------------------------------------------------------------- hip flexors */
  {
    id: 'psoas_major', name: 'Psoas major', latin: 'Musculus psoas major',
    region: 'hip', group: 'iliopsoas', trainableUnitId: 'hip_flexors',
    origin: [at('t12_l5_bodies'), at('lumbar_transverse')],
    insertion: [at('lesser_trochanter')],
    innervation: [inn('lumbar_rami', ['L1', 'L2', 'L3'])],
    actions: [act('hip', 'flexion'), act('spine', 'lateral_flexion', 'assist'),
              act('spine', 'flexion', 'assist', 'with the femur fixed')],
    notes: 'With iliacus forms iliopsoas, the strongest hip flexor.',
    reviewStatus: 'draft',
  },
  {
    id: 'iliacus', name: 'Iliacus', latin: 'Musculus iliacus',
    region: 'hip', group: 'iliopsoas', trainableUnitId: 'hip_flexors',
    origin: [at('iliac_fossa')], insertion: [at('lesser_trochanter')],
    innervation: [inn('femoral', ['L2', 'L3'])],
    actions: [act('hip', 'flexion'), act('hip', 'external_rotation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'sartorius', name: 'Sartorius', latin: 'Musculus sartorius',
    region: 'thigh', trainableUnitId: 'hip_flexors', palpable: true,
    origin: [at('asis')], insertion: [at('pes_anserinus')],
    innervation: [inn('femoral', ['L2', 'L3'])],
    actions: [act('hip', 'flexion'), act('hip', 'abduction', 'assist'),
              act('hip', 'external_rotation', 'assist'), act('knee', 'flexion', 'assist'),
              act('knee', 'internal_rotation', 'assist')],
    notes: 'The longest muscle in the body; produces the cross-legged "tailor" position.',
    reviewStatus: 'draft',
  },
  {
    id: 'tensor_fasciae_latae', name: 'Tensor fasciae latae',
    latin: 'Musculus tensor fasciae latae',
    region: 'hip', trainableUnitId: 'glute_med_min', palpable: true,
    origin: [at('asis'), at('iliac_crest', 'anterior part')],
    insertion: [at('iliotibial_band', 'to the lateral tibial condyle')],
    innervation: [inn('superior_gluteal', ['L4', 'L5', 'S1'])],
    actions: [act('hip', 'abduction'), act('hip', 'flexion', 'assist'),
              act('hip', 'internal_rotation', 'assist'), act('knee', 'extension', 'stabilize')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------------- glutes */
  {
    id: 'gluteus_maximus', name: 'Gluteus maximus', latin: 'Musculus gluteus maximus',
    region: 'hip', trainableUnitId: 'glute_max', palpable: true,
    origin: [at('gluteal_surface', 'posterior to the posterior gluteal line'),
             at('sacrum_posterior'), at('sacrotuberous_ligament'), at('thoracolumbar_fascia')],
    insertion: [at('iliotibial_band', 'about three-quarters of fibres'),
                at('gluteal_tuberosity', 'about one-quarter of fibres')],
    innervation: [inn('inferior_gluteal', ['L5', 'S1', 'S2'])],
    actions: [act('hip', 'extension'), act('hip', 'external_rotation'),
              act('hip', 'abduction', 'assist', 'upper fibres'),
              act('hip', 'adduction', 'assist', 'lower fibres')],
    notes: 'Largest muscle in the body; chiefly recruited above roughly 45° of hip flexion.',
    reviewStatus: 'draft',
  },
  {
    id: 'gluteus_medius', name: 'Gluteus medius', latin: 'Musculus gluteus medius',
    region: 'hip', trainableUnitId: 'glute_med_min',
    origin: [at('gluteal_surface', 'between the anterior and posterior gluteal lines')],
    insertion: [at('greater_trochanter', 'lateral surface')],
    innervation: [inn('superior_gluteal', ['L4', 'L5', 'S1'])],
    actions: [act('hip', 'abduction'),
              act('hip', 'internal_rotation', 'assist', 'anterior fibres'),
              act('hip', 'external_rotation', 'assist', 'posterior fibres')],
    notes: 'Stabilises the pelvis in single-leg stance; weakness gives a Trendelenburg gait.',
    reviewStatus: 'draft',
  },
  {
    id: 'gluteus_minimus', name: 'Gluteus minimus', latin: 'Musculus gluteus minimus',
    region: 'hip', trainableUnitId: 'glute_med_min',
    origin: [at('gluteal_surface', 'between the anterior and inferior gluteal lines')],
    insertion: [at('greater_trochanter', 'anterior surface')],
    innervation: [inn('superior_gluteal', ['L4', 'L5', 'S1'])],
    actions: [act('hip', 'abduction'), act('hip', 'internal_rotation', 'assist')],
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------- deep hip rotators */
  {
    id: 'piriformis', name: 'Piriformis', latin: 'Musculus piriformis',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('anterior_sacroiliac')], insertion: [at('greater_trochanter', 'superior border')],
    innervation: [inn('nerve_to_piriformis', ['S1', 'S2'])],
    actions: [act('hip', 'external_rotation'),
              act('hip', 'abduction', 'assist', 'with the hip flexed')],
    notes: 'The sciatic nerve passes beneath it, and through it in a minority of people.',
    reviewStatus: 'draft',
  },
  {
    id: 'obturator_internus', name: 'Obturator internus', latin: 'Musculus obturator internus',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('obturator_membrane', 'internal surface'), at('obturator_foramen')],
    insertion: [at('greater_trochanter', 'medial surface')],
    innervation: [inn('nerve_to_obturator_internus', ['L5', 'S1', 'S2'])],
    actions: [act('hip', 'external_rotation'), act('hip', 'abduction', 'assist', 'hip flexed')],
    reviewStatus: 'draft',
  },
  {
    id: 'obturator_externus', name: 'Obturator externus', latin: 'Musculus obturator externus',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('obturator_membrane', 'external surface')],
    insertion: [at('trochanteric_fossa')],
    innervation: [inn('obturator', ['L3', 'L4'])],
    actions: [act('hip', 'external_rotation'), act('hip', 'adduction', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'gemellus_superior', name: 'Superior gemellus', latin: 'Musculus gemellus superior',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('ischial_spine')], insertion: [at('greater_trochanter', 'medial surface')],
    innervation: [inn('nerve_to_obturator_internus', ['L5', 'S1', 'S2'])],
    actions: [act('hip', 'external_rotation')],
    reviewStatus: 'draft',
  },
  {
    id: 'gemellus_inferior', name: 'Inferior gemellus', latin: 'Musculus gemellus inferior',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('ischial_tuberosity')], insertion: [at('greater_trochanter', 'medial surface')],
    innervation: [inn('nerve_to_quadratus_femoris', ['L4', 'L5', 'S1'])],
    actions: [act('hip', 'external_rotation')],
    reviewStatus: 'draft',
  },
  {
    id: 'quadratus_femoris', name: 'Quadratus femoris', latin: 'Musculus quadratus femoris',
    region: 'hip', group: 'deep hip rotators', trainableUnitId: 'glute_med_min',
    origin: [at('ischial_tuberosity', 'lateral border')],
    insertion: [at('intertrochanteric_crest', 'quadrate tubercle')],
    innervation: [inn('nerve_to_quadratus_femoris', ['L4', 'L5', 'S1'])],
    actions: [act('hip', 'external_rotation'), act('hip', 'adduction', 'assist')],
    reviewStatus: 'draft',
  },

  /* ---------------------------------------------------------------- adductors */
  {
    id: 'pectineus', name: 'Pectineus', latin: 'Musculus pectineus',
    region: 'thigh', group: 'adductors', trainableUnitId: 'adductors',
    origin: [at('pectineal_line_pubis')], insertion: [at('pectineal_line_femur')],
    innervation: [inn('femoral', ['L2', 'L3']), inn('obturator', ['L2', 'L3'], 'variable')],
    actions: [act('hip', 'adduction'), act('hip', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'adductor_longus', name: 'Adductor longus', latin: 'Musculus adductor longus',
    region: 'thigh', group: 'adductors', trainableUnitId: 'adductors',
    origin: [at('pubic_body', 'below the pubic crest')],
    insertion: [at('linea_aspera', 'middle third')],
    innervation: [inn('obturator', ['L2', 'L3', 'L4'])],
    actions: [act('hip', 'adduction'), act('hip', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'adductor_brevis', name: 'Adductor brevis', latin: 'Musculus adductor brevis',
    region: 'thigh', group: 'adductors', trainableUnitId: 'adductors',
    origin: [at('pubic_body'), at('pubic_ramus_inferior')],
    insertion: [at('pectineal_line_femur'), at('linea_aspera', 'proximal part')],
    innervation: [inn('obturator', ['L2', 'L3', 'L4'])],
    actions: [act('hip', 'adduction'), act('hip', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'adductor_magnus', name: 'Adductor magnus', latin: 'Musculus adductor magnus',
    region: 'thigh', group: 'adductors', trainableUnitId: 'adductors',
    origin: [at('pubic_ramus_inferior', 'adductor part'), at('ischial_ramus'),
             at('ischial_tuberosity', 'hamstring part')],
    insertion: [at('linea_aspera', 'adductor part'), at('adductor_tubercle', 'hamstring part')],
    innervation: [inn('obturator', ['L2', 'L3', 'L4'], 'adductor part'),
                  inn('tibial', ['L4'], 'hamstring part')],
    actions: [act('hip', 'adduction'),
              act('hip', 'extension', 'prime', 'hamstring part'),
              act('hip', 'flexion', 'assist', 'adductor part')],
    notes: 'Dual innervation and opposing hip actions between its two parts.',
    reviewStatus: 'draft',
  },
  {
    id: 'gracilis', name: 'Gracilis', latin: 'Musculus gracilis',
    region: 'thigh', group: 'adductors', trainableUnitId: 'adductors',
    origin: [at('pubic_body'), at('pubic_ramus_inferior')],
    insertion: [at('pes_anserinus')],
    innervation: [inn('obturator', ['L2', 'L3'])],
    actions: [act('hip', 'adduction'), act('knee', 'flexion', 'assist'),
              act('knee', 'internal_rotation', 'assist')],
    notes: 'The only adductor crossing the knee.',
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------------- quads */
  {
    id: 'rectus_femoris', name: 'Rectus femoris', latin: 'Musculus rectus femoris',
    region: 'thigh', group: 'quadriceps', trainableUnitId: 'quads_rf', palpable: true,
    origin: [at('aiis', 'straight head'), at('acetabulum', 'reflected head, superior rim')],
    insertion: [at('patella_base', 'then the tibial tuberosity via the patellar ligament')],
    innervation: [inn('femoral', ['L2', 'L3', 'L4'])],
    actions: [act('knee', 'extension'), act('hip', 'flexion')],
    notes: 'The only quadriceps head crossing the hip, so hip position changes its length — '
         + 'which is why a reclined torso biases it in leg extensions.',
    reviewStatus: 'draft',
  },
  {
    id: 'vastus_lateralis', name: 'Vastus lateralis', latin: 'Musculus vastus lateralis',
    region: 'thigh', group: 'quadriceps', trainableUnitId: 'quads_vasti', palpable: true,
    origin: [at('greater_trochanter'), at('linea_aspera', 'lateral lip')],
    insertion: [at('patella_base')],
    innervation: [inn('femoral', ['L2', 'L3', 'L4'])],
    actions: [act('knee', 'extension')],
    reviewStatus: 'draft',
  },
  {
    id: 'vastus_medialis', name: 'Vastus medialis', latin: 'Musculus vastus medialis',
    region: 'thigh', group: 'quadriceps', trainableUnitId: 'quads_vasti', palpable: true,
    origin: [at('intertrochanteric_line'), at('linea_aspera', 'medial lip')],
    insertion: [at('patella_base')],
    innervation: [inn('femoral', ['L2', 'L3', 'L4'])],
    actions: [act('knee', 'extension'), act('knee', 'extension', 'stabilize', 'patellar tracking')],
    reviewStatus: 'draft',
  },
  {
    id: 'vastus_intermedius', name: 'Vastus intermedius', latin: 'Musculus vastus intermedius',
    region: 'thigh', group: 'quadriceps', trainableUnitId: 'quads_vasti',
    origin: [at('femur_shaft_anterior', 'anterior and lateral surfaces')],
    insertion: [at('patella_base')],
    innervation: [inn('femoral', ['L2', 'L3', 'L4'])],
    actions: [act('knee', 'extension')],
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------------- hamstrings */
  {
    id: 'biceps_femoris', name: 'Biceps femoris', latin: 'Musculus biceps femoris',
    region: 'thigh', group: 'hamstrings', trainableUnitId: 'hamstrings', palpable: true,
    origin: [at('ischial_tuberosity', 'long head'),
             at('linea_aspera', 'short head'), at('lateral_supracondylar_line', 'short head')],
    insertion: [at('fibula_head')],
    innervation: [inn('tibial', ['L5', 'S1', 'S2'], 'long head'),
                  inn('common_fibular', ['L5', 'S1', 'S2'], 'short head')],
    actions: [act('knee', 'flexion'), act('hip', 'extension', 'prime', 'long head only'),
              act('knee', 'external_rotation', 'assist')],
    notes: 'Split innervation between its heads, like adductor magnus.',
    reviewStatus: 'draft',
  },
  {
    id: 'semitendinosus', name: 'Semitendinosus', latin: 'Musculus semitendinosus',
    region: 'thigh', group: 'hamstrings', trainableUnitId: 'hamstrings',
    origin: [at('ischial_tuberosity')], insertion: [at('pes_anserinus')],
    innervation: [inn('tibial', ['L5', 'S1', 'S2'])],
    actions: [act('knee', 'flexion'), act('hip', 'extension'),
              act('knee', 'internal_rotation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'semimembranosus', name: 'Semimembranosus', latin: 'Musculus semimembranosus',
    region: 'thigh', group: 'hamstrings', trainableUnitId: 'hamstrings',
    origin: [at('ischial_tuberosity')],
    insertion: [at('tibia_medial_condyle', 'posterior aspect')],
    innervation: [inn('tibial', ['L5', 'S1', 'S2'])],
    actions: [act('knee', 'flexion'), act('hip', 'extension'),
              act('knee', 'internal_rotation', 'assist')],
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------------------- calf */
  {
    id: 'gastrocnemius', name: 'Gastrocnemius', latin: 'Musculus gastrocnemius',
    region: 'leg', group: 'triceps surae', trainableUnitId: 'calves_gastroc', palpable: true,
    origin: [at('femur_condyle_medial', 'medial head'), at('femur_condyle_lateral', 'lateral head')],
    insertion: [at('calcaneus', 'via the calcaneal tendon')],
    innervation: [inn('tibial', ['S1', 'S2'])],
    actions: [act('ankle', 'plantarflexion'), act('knee', 'flexion', 'assist')],
    notes: 'Crosses the knee, so it shortens with the knee bent — which is why seated calf '
         + 'raises bias soleus and standing ones bias gastrocnemius.',
    reviewStatus: 'draft',
  },
  {
    id: 'soleus', name: 'Soleus', latin: 'Musculus soleus',
    region: 'leg', group: 'triceps surae', trainableUnitId: 'calves_soleus',
    origin: [at('soleal_line'), at('tibia_shaft_posterior'), at('fibula_head'),
             at('fibula_shaft_posterior', 'proximal third')],
    insertion: [at('calcaneus', 'via the calcaneal tendon')],
    innervation: [inn('tibial', ['S1', 'S2'])],
    actions: [act('ankle', 'plantarflexion')],
    reviewStatus: 'draft',
  },
  {
    id: 'plantaris', name: 'Plantaris', latin: 'Musculus plantaris',
    region: 'leg', trainableUnitId: 'calves_gastroc',
    origin: [at('lateral_supracondylar_line')], insertion: [at('calcaneus')],
    innervation: [inn('tibial', ['S1', 'S2'])],
    actions: [act('ankle', 'plantarflexion', 'assist'), act('knee', 'flexion', 'assist')],
    notes: 'Absent in roughly 10% of people.',
    reviewStatus: 'draft',
  },
  {
    id: 'popliteus', name: 'Popliteus', latin: 'Musculus popliteus',
    region: 'leg', trainableUnitId: 'hamstrings',
    origin: [at('femur_condyle_lateral')], insertion: [at('tibia_shaft_posterior', 'above the soleal line')],
    innervation: [inn('tibial', ['L4', 'L5', 'S1'])],
    actions: [act('knee', 'internal_rotation', 'prime', 'of the tibia; "unlocks" the extended knee'),
              act('knee', 'flexion', 'assist')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------- anterior compartment */
  {
    id: 'tibialis_anterior', name: 'Tibialis anterior', latin: 'Musculus tibialis anterior',
    region: 'leg', compartment: 'anterior leg', trainableUnitId: 'tibialis_ant', palpable: true,
    origin: [at('tibia_lateral_condyle'), at('tibia_shaft_lateral', 'proximal half'),
             at('interosseous_membrane_leg')],
    insertion: [at('medial_cuneiform'), at('metatarsal_1_base')],
    innervation: [inn('deep_fibular', ['L4', 'L5'])],
    actions: [act('ankle', 'dorsiflexion'), act('subtalar', 'inversion')],
    notes: 'Deep fibular palsy gives foot drop.',
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_digitorum_longus', name: 'Extensor digitorum longus',
    latin: 'Musculus extensor digitorum longus',
    region: 'leg', compartment: 'anterior leg', trainableUnitId: 'tibialis_ant',
    origin: [at('tibia_lateral_condyle'), at('fibula_shaft_lateral', 'anterior surface'),
             at('interosseous_membrane_leg')],
    insertion: [at('phalanges_middle_foot', 'digits 2–5'), at('phalanges_distal_foot', 'digits 2–5')],
    innervation: [inn('deep_fibular', ['L5', 'S1'])],
    actions: [act('toes', 'extension'), act('ankle', 'dorsiflexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_hallucis_longus', name: 'Extensor hallucis longus',
    latin: 'Musculus extensor hallucis longus',
    region: 'leg', compartment: 'anterior leg', trainableUnitId: 'tibialis_ant',
    origin: [at('fibula_shaft_lateral', 'middle anterior surface'), at('interosseous_membrane_leg')],
    insertion: [at('hallux_distal')],
    innervation: [inn('deep_fibular', ['L5', 'S1'])],
    actions: [act('toes', 'extension', 'prime', 'great toe'), act('ankle', 'dorsiflexion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'fibularis_tertius', name: 'Fibularis tertius', latin: 'Musculus fibularis tertius',
    region: 'leg', compartment: 'anterior leg', trainableUnitId: 'tibialis_ant',
    origin: [at('fibula_shaft_lateral', 'distal anterior')], insertion: [at('metatarsal_5_base')],
    innervation: [inn('deep_fibular', ['L5', 'S1'])],
    actions: [act('ankle', 'dorsiflexion', 'assist'), act('subtalar', 'eversion', 'assist')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------- lateral compartment */
  {
    id: 'fibularis_longus', name: 'Fibularis longus', latin: 'Musculus fibularis longus',
    region: 'leg', compartment: 'lateral leg', trainableUnitId: 'calves_soleus',
    origin: [at('fibula_head'), at('fibula_shaft_lateral', 'proximal two-thirds')],
    insertion: [at('medial_cuneiform'), at('metatarsal_1_base')],
    innervation: [inn('superficial_fibular', ['L5', 'S1', 'S2'])],
    actions: [act('subtalar', 'eversion'), act('ankle', 'plantarflexion', 'assist')],
    notes: 'Crosses the sole of the foot to reach the medial side, supporting the arches.',
    reviewStatus: 'draft',
  },
  {
    id: 'fibularis_brevis', name: 'Fibularis brevis', latin: 'Musculus fibularis brevis',
    region: 'leg', compartment: 'lateral leg', trainableUnitId: 'calves_soleus',
    origin: [at('fibula_shaft_lateral', 'distal two-thirds')],
    insertion: [at('metatarsal_5_base', 'tuberosity')],
    innervation: [inn('superficial_fibular', ['L5', 'S1', 'S2'])],
    actions: [act('subtalar', 'eversion'), act('ankle', 'plantarflexion', 'assist')],
    reviewStatus: 'draft',
  },

  /* --------------------------------------------------- deep posterior compartment */
  {
    id: 'tibialis_posterior', name: 'Tibialis posterior', latin: 'Musculus tibialis posterior',
    region: 'leg', compartment: 'deep posterior leg', trainableUnitId: 'calves_soleus',
    origin: [at('tibia_shaft_posterior'), at('fibula_shaft_posterior'),
             at('interosseous_membrane_leg')],
    insertion: [at('navicular'), at('cuneiforms'), at('metatarsals_2_4_base')],
    innervation: [inn('tibial', ['L4', 'L5'])],
    actions: [act('subtalar', 'inversion'), act('ankle', 'plantarflexion', 'assist')],
    notes: 'The main dynamic support of the medial longitudinal arch.',
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_digitorum_longus_foot', name: 'Flexor digitorum longus',
    latin: 'Musculus flexor digitorum longus',
    region: 'leg', compartment: 'deep posterior leg', trainableUnitId: 'calves_soleus',
    origin: [at('tibia_shaft_posterior', 'below the soleal line')],
    insertion: [at('phalanges_distal_foot', 'digits 2–5')],
    innervation: [inn('tibial', ['L5', 'S1'])],
    actions: [act('toes', 'flexion'), act('ankle', 'plantarflexion', 'assist'),
              act('subtalar', 'inversion', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_hallucis_longus', name: 'Flexor hallucis longus',
    latin: 'Musculus flexor hallucis longus',
    region: 'leg', compartment: 'deep posterior leg', trainableUnitId: 'calves_soleus',
    origin: [at('fibula_shaft_posterior', 'distal two-thirds'), at('interosseous_membrane_leg')],
    insertion: [at('hallux_distal')],
    innervation: [inn('tibial', ['L5', 'S1', 'S2'])],
    actions: [act('toes', 'flexion', 'prime', 'great toe'),
              act('ankle', 'plantarflexion', 'assist')],
    notes: 'Provides the final push-off in gait.',
    reviewStatus: 'draft',
  },
]
