/** Abdominal wall, back extensors and neck. reviewStatus is 'draft' throughout
 *  — see docs/anatomy-model.md §5. */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const TRUNK_MUSCLES: AnatomicalMuscle[] = [
  /* ---------------------------------------------------------- abdominal wall */
  {
    id: 'rectus_abdominis', name: 'Rectus abdominis', latin: 'Musculus rectus abdominis',
    region: 'abdomen', trainableUnitId: 'rectus_abdominis', palpable: true,
    origin: [at('pubic_crest'), at('pubic_symphysis')],
    insertion: [at('xiphoid_process'), at('costal_cartilages_5_7')],
    innervation: [inn('thoracoabdominal', ['T7', 'T8', 'T9', 'T10', 'T11']),
                  inn('subcostal', ['T12'])],
    actions: [act('spine', 'flexion'), act('spine', 'lateral_flexion', 'assist')],
    notes: 'Segmented by tendinous intersections, which is why it appears as "abs" — '
         + 'the number of visible segments is genetic, not trainable.',
    reviewStatus: 'draft',
  },
  {
    id: 'external_oblique', name: 'External oblique', latin: 'Musculus obliquus externus abdominis',
    region: 'abdomen', trainableUnitId: 'obliques', palpable: true,
    origin: [at('ribs_5_12_outer')],
    insertion: [at('iliac_crest'), at('linea_alba'), at('inguinal_ligament')],
    innervation: [inn('thoracoabdominal', ['T7', 'T8', 'T9', 'T10', 'T11']),
                  inn('subcostal', ['T12'])],
    actions: [act('spine', 'flexion'), act('spine', 'lateral_flexion', 'prime', 'ipsilateral'),
              act('spine', 'rotation', 'prime', 'contralateral')],
    notes: 'Fibres run downward and forward, like hands in front pockets.',
    reviewStatus: 'draft',
  },
  {
    id: 'internal_oblique', name: 'Internal oblique', latin: 'Musculus obliquus internus abdominis',
    region: 'abdomen', trainableUnitId: 'obliques',
    origin: [at('thoracolumbar_fascia'), at('iliac_crest_inner'), at('inguinal_ligament')],
    insertion: [at('ribs_10_12'), at('linea_alba')],
    innervation: [inn('thoracoabdominal', ['T7', 'T8', 'T9', 'T10', 'T11']),
                  inn('subcostal', ['T12']), inn('iliohypogastric', ['L1'])],
    actions: [act('spine', 'flexion'), act('spine', 'lateral_flexion', 'prime', 'ipsilateral'),
              act('spine', 'rotation', 'prime', 'ipsilateral')],
    notes: 'Rotates the trunk to the same side, opposite to the external oblique — '
         + 'so a rotation pairs one side\'s external with the other side\'s internal.',
    reviewStatus: 'draft',
  },
  {
    id: 'transversus_abdominis', name: 'Transversus abdominis',
    latin: 'Musculus transversus abdominis',
    region: 'abdomen', trainableUnitId: 'obliques',
    origin: [at('ribs_lower_inner', 'costal cartilages 7–12'), at('thoracolumbar_fascia'),
             at('iliac_crest_inner'), at('inguinal_ligament')],
    insertion: [at('linea_alba'), at('pubic_crest')],
    innervation: [inn('thoracoabdominal', ['T7', 'T8', 'T9', 'T10', 'T11']),
                  inn('subcostal', ['T12']), inn('iliohypogastric', ['L1'])],
    actions: [act('spine', 'flexion', 'stabilize', 'compresses the abdomen; raises intra-abdominal pressure')],
    notes: 'The deepest abdominal layer; what a lifting belt gives something to brace against.',
    reviewStatus: 'draft',
  },
  {
    id: 'quadratus_lumborum', name: 'Quadratus lumborum', latin: 'Musculus quadratus lumborum',
    region: 'abdomen', trainableUnitId: 'erectors',
    origin: [at('iliac_crest'), at('iliolumbar_ligament')],
    insertion: [at('rib_12'), at('lumbar_transverse', 'L1–L4')],
    innervation: [inn('subcostal', ['T12']), inn('lumbar_rami', ['L1', 'L2', 'L3', 'L4'])],
    actions: [act('spine', 'lateral_flexion', 'prime', 'ipsilateral'),
              act('spine', 'extension', 'assist')],
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------------- back extensors */
  {
    id: 'iliocostalis', name: 'Iliocostalis', latin: 'Musculus iliocostalis',
    region: 'back', group: 'erector spinae', trainableUnitId: 'erectors',
    origin: [at('sacrum_iliac_common')],
    insertion: [at('ribs_lower', 'angles of the ribs'), at('cervical_transverse_all')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension'), act('spine', 'lateral_flexion', 'prime', 'ipsilateral')],
    notes: 'The most lateral of the three erector spinae columns.',
    reviewStatus: 'draft',
  },
  {
    id: 'longissimus', name: 'Longissimus', latin: 'Musculus longissimus',
    region: 'back', group: 'erector spinae', trainableUnitId: 'erectors',
    origin: [at('sacrum_iliac_common'), at('thoracic_transverse')],
    insertion: [at('thoracic_transverse'), at('ribs_lower'), at('mastoid_process')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension'), act('spine', 'lateral_flexion', 'prime', 'ipsilateral')],
    notes: 'The intermediate and largest erector column.',
    reviewStatus: 'draft',
  },
  {
    id: 'spinalis', name: 'Spinalis', latin: 'Musculus spinalis',
    region: 'back', group: 'erector spinae', trainableUnitId: 'erectors',
    origin: [at('t7_l5_spinous', 'upper lumbar and lower thoracic')],
    insertion: [at('t3_t6_spinous', 'upper thoracic')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension')],
    notes: 'The most medial erector column, lying against the spinous processes.',
    reviewStatus: 'draft',
  },
  {
    id: 'multifidus', name: 'Multifidus', latin: 'Musculus multifidus',
    region: 'back', group: 'transversospinalis', trainableUnitId: 'erectors',
    origin: [at('sacrum_posterior'), at('lumbar_transverse'), at('thoracic_transverse')],
    insertion: [at('spinous_processes_general', 'two to four levels above')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension', 'assist'),
              act('spine', 'rotation', 'assist', 'contralateral'),
              act('spine', 'extension', 'stabilize', 'segmental control')],
    notes: 'Thickest in the lumbar spine; a major segmental stabiliser.',
    reviewStatus: 'draft',
  },
  {
    id: 'semispinalis_capitis', name: 'Semispinalis capitis',
    latin: 'Musculus semispinalis capitis',
    region: 'back', group: 'transversospinalis', trainableUnitId: 'neck',
    origin: [at('c7_t6_transverse')],
    insertion: [at('occipital_between_nuchal_lines')],
    innervation: [inn('dorsal_rami_cervical', ['C1', 'C2', 'C3', 'C4', 'C5'])],
    actions: [act('cervical_spine_joint', 'extension'),
              act('cervical_spine_joint', 'rotation', 'assist', 'contralateral')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------------- neck */
  {
    id: 'sternocleidomastoid', name: 'Sternocleidomastoid',
    latin: 'Musculus sternocleidomastoideus',
    region: 'neck', trainableUnitId: 'neck', palpable: true,
    origin: [at('manubrium', 'sternal head'), at('clavicle_medial', 'clavicular head')],
    insertion: [at('mastoid_process'), at('nuchal_line_superior', 'lateral half')],
    innervation: [inn('accessory', ['CN XI'], 'motor'),
                  inn('cervical_rami', ['C2', 'C3'], 'proprioceptive')],
    actions: [act('cervical_spine_joint', 'rotation', 'prime', 'contralateral'),
              act('cervical_spine_joint', 'lateral_flexion', 'prime', 'ipsilateral'),
              act('cervical_spine_joint', 'flexion', 'prime', 'both sides together')],
    notes: 'Turns the head to the opposite side — the classic "look over your shoulder" test.',
    reviewStatus: 'draft',
  },
  {
    id: 'scalenus_anterior', name: 'Anterior scalene', latin: 'Musculus scalenus anterior',
    region: 'neck', group: 'scalenes', trainableUnitId: 'neck',
    origin: [at('c4_c6_transverse', 'C3–C6 anterior tubercles')], insertion: [at('rib_1')],
    innervation: [inn('cervical_rami', ['C4', 'C5', 'C6'])],
    actions: [act('cervical_spine_joint', 'lateral_flexion', 'prime', 'ipsilateral'),
              act('cervical_spine_joint', 'flexion', 'assist')],
    notes: 'The brachial plexus and subclavian artery pass between anterior and middle scalene.',
    reviewStatus: 'draft',
  },
  {
    id: 'scalenus_medius', name: 'Middle scalene', latin: 'Musculus scalenus medius',
    region: 'neck', group: 'scalenes', trainableUnitId: 'neck',
    origin: [at('cervical_transverse_all', 'C2–C7 posterior tubercles')], insertion: [at('rib_1')],
    innervation: [inn('cervical_rami', ['C3', 'C4', 'C5', 'C6', 'C7', 'C8'])],
    actions: [act('cervical_spine_joint', 'lateral_flexion', 'prime', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'scalenus_posterior', name: 'Posterior scalene', latin: 'Musculus scalenus posterior',
    region: 'neck', group: 'scalenes', trainableUnitId: 'neck',
    origin: [at('c4_c6_transverse', 'C5–C7 posterior tubercles')], insertion: [at('rib_2')],
    innervation: [inn('cervical_rami', ['C6', 'C7', 'C8'])],
    actions: [act('cervical_spine_joint', 'lateral_flexion', 'assist', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'splenius_capitis', name: 'Splenius capitis', latin: 'Musculus splenius capitis',
    region: 'neck', trainableUnitId: 'neck',
    origin: [at('nuchal_ligament'), at('c7_t12_spinous', 'C7–T3')],
    insertion: [at('mastoid_process'), at('nuchal_line_superior')],
    innervation: [inn('dorsal_rami_cervical', ['C3', 'C4', 'C5'])],
    actions: [act('cervical_spine_joint', 'extension'),
              act('cervical_spine_joint', 'rotation', 'prime', 'ipsilateral'),
              act('cervical_spine_joint', 'lateral_flexion', 'assist', 'ipsilateral')],
    notes: 'Rotates the head to the same side — opposite to sternocleidomastoid.',
    reviewStatus: 'draft',
  },
  {
    id: 'splenius_cervicis', name: 'Splenius cervicis', latin: 'Musculus splenius cervicis',
    region: 'neck', trainableUnitId: 'neck',
    origin: [at('t3_t6_spinous')], insertion: [at('c1_c3_transverse')],
    innervation: [inn('dorsal_rami_cervical', ['C5', 'C6', 'C7', 'C8'])],
    actions: [act('cervical_spine_joint', 'extension'),
              act('cervical_spine_joint', 'rotation', 'prime', 'ipsilateral')],
    reviewStatus: 'draft',
  },
]
