/** Deep forearm muscles acting on the digits, and the intrinsic muscles of the
 *  hand. None of these carry a trainableUnitId: the engine has no business
 *  programming the third palmar interosseous, and the layering means it never
 *  sees them. See docs/anatomy-model.md §1 */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const HAND_MUSCLES: AnatomicalMuscle[] = [
  /* ------------------------------------- deep forearm, acting on the digits */
  {
    id: 'flexor_pollicis_longus', name: 'Flexor pollicis longus',
    latin: 'Musculus flexor pollicis longus', region: 'forearm',
    compartment: 'anterior forearm (deep)',
    origin: [at('radius_shaft', 'anterior surface'), at('interosseous_membrane_forearm')],
    insertion: [at('thumb_distal_phalanx')],
    innervation: [inn('anterior_interosseous', ['C7', 'C8'])],
    actions: [act('fingers', 'flexion', 'prime', 'interphalangeal joint of the thumb')],
    reviewStatus: 'draft',
  },
  {
    id: 'abductor_pollicis_longus', name: 'Abductor pollicis longus',
    latin: 'Musculus abductor pollicis longus', region: 'forearm',
    compartment: 'posterior forearm (deep)',
    origin: [at('ulna_shaft', 'posterior'), at('radius_shaft', 'posterior'),
             at('interosseous_membrane_forearm')],
    insertion: [at('metacarpal_1_base')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('thumb_cmc', 'abduction'), act('thumb_cmc', 'extension', 'assist'),
              act('wrist', 'abduction', 'assist')],
    notes: 'With extensor pollicis brevis forms the radial border of the anatomical snuffbox.',
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_pollicis_brevis', name: 'Extensor pollicis brevis',
    latin: 'Musculus extensor pollicis brevis', region: 'forearm',
    compartment: 'posterior forearm (deep)',
    origin: [at('radius_shaft', 'posterior'), at('interosseous_membrane_forearm')],
    insertion: [at('thumb_proximal_phalanx')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('thumb_cmc', 'extension'), act('wrist', 'abduction', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_pollicis_longus', name: 'Extensor pollicis longus',
    latin: 'Musculus extensor pollicis longus', region: 'forearm',
    compartment: 'posterior forearm (deep)',
    origin: [at('ulna_shaft', 'posterior'), at('interosseous_membrane_forearm')],
    insertion: [at('thumb_distal_phalanx')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('thumb_cmc', 'extension'), act('fingers', 'extension', 'prime', 'thumb IP joint')],
    notes: 'Forms the ulnar border of the anatomical snuffbox; hooks around Lister\'s tubercle.',
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_indicis', name: 'Extensor indicis', latin: 'Musculus extensor indicis',
    region: 'forearm', compartment: 'posterior forearm (deep)',
    origin: [at('ulna_shaft', 'posterior'), at('interosseous_membrane_forearm')],
    insertion: [at('extensor_expansion', 'index finger')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('fingers', 'extension', 'prime', 'index finger')],
    reviewStatus: 'draft',
  },
  {
    id: 'extensor_digiti_minimi', name: 'Extensor digiti minimi',
    latin: 'Musculus extensor digiti minimi', region: 'forearm',
    compartment: 'posterior forearm',
    origin: [at('lateral_epicondyle', 'common extensor origin')],
    insertion: [at('extensor_expansion', 'little finger')],
    innervation: [inn('posterior_interosseous', ['C7', 'C8'])],
    actions: [act('fingers', 'extension', 'prime', 'little finger')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------ thenar group */
  {
    id: 'abductor_pollicis_brevis', name: 'Abductor pollicis brevis',
    latin: 'Musculus abductor pollicis brevis', region: 'hand', group: 'thenar',
    origin: [at('flexor_retinaculum'), at('scaphoid_tubercle'), at('trapezium_tubercle')],
    insertion: [at('thumb_proximal_phalanx', 'lateral side')],
    innervation: [inn('median_recurrent', ['C8', 'T1'])],
    actions: [act('thumb_cmc', 'abduction')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_pollicis_brevis', name: 'Flexor pollicis brevis',
    latin: 'Musculus flexor pollicis brevis', region: 'hand', group: 'thenar',
    origin: [at('flexor_retinaculum'), at('trapezium_tubercle')],
    insertion: [at('thumb_proximal_phalanx')],
    innervation: [inn('median_recurrent', ['C8', 'T1'], 'superficial head'),
                  inn('ulnar_deep', ['C8', 'T1'], 'deep head')],
    actions: [act('thumb_cmc', 'flexion')],
    reviewStatus: 'draft',
  },
  {
    id: 'opponens_pollicis', name: 'Opponens pollicis', latin: 'Musculus opponens pollicis',
    region: 'hand', group: 'thenar',
    origin: [at('flexor_retinaculum'), at('trapezium_tubercle')],
    insertion: [at('metacarpal_1_shaft', 'lateral border')],
    innervation: [inn('median_recurrent', ['C8', 'T1'])],
    actions: [act('thumb_cmc', 'opposition')],
    notes: 'Opposition is the movement that makes the human hand what it is; '
         + 'lost in recurrent-branch injury.',
    reviewStatus: 'draft',
  },
  {
    id: 'adductor_pollicis', name: 'Adductor pollicis', latin: 'Musculus adductor pollicis',
    region: 'hand', group: 'thenar',
    origin: [at('capitate_body', 'oblique head'),
             at('metacarpal_shafts', 'transverse head, 3rd metacarpal')],
    insertion: [at('thumb_proximal_phalanx', 'medial side')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('thumb_cmc', 'adduction')],
    notes: 'Its weakness gives Froment\'s sign in ulnar nerve palsy.',
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------- hypothenar group */
  {
    id: 'abductor_digiti_minimi_manus', name: 'Abductor digiti minimi (hand)',
    latin: 'Musculus abductor digiti minimi manus', region: 'hand', group: 'hypothenar',
    origin: [at('pisiform')],
    insertion: [at('phalanges_proximal_hand', 'little finger, medial side')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('fingers', 'abduction', 'prime', 'little finger')],
    reviewStatus: 'draft',
  },
  {
    id: 'flexor_digiti_minimi_brevis_manus', name: 'Flexor digiti minimi brevis (hand)',
    latin: 'Musculus flexor digiti minimi brevis manus', region: 'hand', group: 'hypothenar',
    origin: [at('hamate_hook'), at('flexor_retinaculum')],
    insertion: [at('phalanges_proximal_hand', 'little finger')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('fingers', 'flexion', 'prime', 'little finger MCP joint')],
    reviewStatus: 'draft',
  },
  {
    id: 'opponens_digiti_minimi', name: 'Opponens digiti minimi',
    latin: 'Musculus opponens digiti minimi', region: 'hand', group: 'hypothenar',
    origin: [at('hamate_hook'), at('flexor_retinaculum')],
    insertion: [at('metacarpal_5_shaft')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('fingers', 'opposition', 'prime', 'little finger')],
    reviewStatus: 'draft',
  },
  {
    id: 'palmaris_brevis', name: 'Palmaris brevis', latin: 'Musculus palmaris brevis',
    region: 'hand', group: 'hypothenar',
    origin: [at('palmar_aponeurosis'), at('flexor_retinaculum')],
    insertion: [at('palmar_skin')],
    innervation: [inn('ulnar_superficial', ['C8', 'T1'])],
    actions: [act('fingers', 'flexion', 'stabilize', 'wrinkles the skin to improve grip')],
    notes: 'The only muscle inserting purely into skin in the hand.',
    reviewStatus: 'draft',
  },

  /* --------------------------------------------------------------- deep hand */
  {
    id: 'lumbricals_hand', name: 'Lumbricals of the hand', latin: 'Musculi lumbricales manus',
    region: 'hand', group: 'deep hand',
    origin: [at('fdp_tendons')],
    insertion: [at('extensor_expansion', 'digits 2–5, radial side')],
    innervation: [inn('median', ['C8', 'T1'], '1st and 2nd'),
                  inn('ulnar_deep', ['C8', 'T1'], '3rd and 4th')],
    actions: [act('fingers', 'flexion', 'prime', 'MCP joints'),
              act('fingers', 'extension', 'prime', 'IP joints')],
    notes: 'Flex where they cross in front and extend where they cross behind — '
         + 'the origin is a tendon, not bone, which is unusual.',
    reviewStatus: 'draft',
  },
  {
    id: 'dorsal_interossei_hand', name: 'Dorsal interossei of the hand',
    latin: 'Musculi interossei dorsales manus', region: 'hand', group: 'deep hand',
    origin: [at('metacarpal_shafts', 'adjacent sides, bipennate')],
    insertion: [at('phalanges_proximal_hand', 'digits 2–4'), at('extensor_expansion')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('fingers', 'abduction'), act('fingers', 'flexion', 'assist', 'MCP joints')],
    notes: 'DAB — Dorsals ABduct. Four of them.',
    reviewStatus: 'draft',
  },
  {
    id: 'palmar_interossei', name: 'Palmar interossei', latin: 'Musculi interossei palmares',
    region: 'hand', group: 'deep hand',
    origin: [at('metacarpal_shafts', 'digits 2, 4 and 5, unipennate')],
    insertion: [at('phalanges_proximal_hand'), at('extensor_expansion')],
    innervation: [inn('ulnar_deep', ['C8', 'T1'])],
    actions: [act('fingers', 'adduction'), act('fingers', 'flexion', 'assist', 'MCP joints')],
    notes: 'PAD — Palmars ADduct. Three of them.',
    reviewStatus: 'draft',
  },
]
