/** Respiratory muscles, the deep transversospinalis layer, and the pelvic
 *  floor. See docs/anatomy-model.md §1 for why most of these carry no
 *  trainableUnitId. */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const THORAX_MUSCLES: AnatomicalMuscle[] = [
  /* ------------------------------------------------------------ respiratory */
  {
    id: 'diaphragm', name: 'Diaphragm', latin: 'Diaphragma', region: 'thorax',
    group: 'respiratory',
    origin: [at('xiphoid_process'), at('costal_margin'), at('l1_l3_bodies', 'right and left crura')],
    insertion: [at('central_tendon')],
    innervation: [inn('phrenic', ['C3', 'C4', 'C5'])],
    actions: [],
    functions: ['The primary muscle of inspiration — flattens to enlarge the thorax',
                'Raises intra-abdominal pressure during a Valsalva manoeuvre'],
    notes: 'C3, 4, 5 keeps the diaphragm alive. Pierced by the IVC (T8), oesophagus (T10) '
         + 'and aorta (T12).',
    reviewStatus: 'draft',
  },
  {
    id: 'external_intercostal', name: 'External intercostals',
    latin: 'Musculi intercostales externi', region: 'thorax', group: 'respiratory',
    origin: [at('rib_borders', 'inferior border of the rib above')],
    insertion: [at('rib_borders', 'superior border of the rib below')],
    innervation: [inn('intercostal', ['T1', 'T2', 'T3', 'T4', 'T5', 'T6',
                                      'T7', 'T8', 'T9', 'T10', 'T11'])],
    actions: [act('costovertebral', 'elevation')],
    functions: ['Elevate the ribs during inspiration'],
    notes: 'Fibres run downward and forward, in the same direction as external oblique.',
    reviewStatus: 'draft',
  },
  {
    id: 'internal_intercostal', name: 'Internal intercostals',
    latin: 'Musculi intercostales interni', region: 'thorax', group: 'respiratory',
    origin: [at('rib_borders', 'superior border of the rib below')],
    insertion: [at('rib_borders', 'inferior border of the rib above')],
    innervation: [inn('intercostal', ['T1', 'T2', 'T3', 'T4', 'T5', 'T6',
                                      'T7', 'T8', 'T9', 'T10', 'T11'])],
    actions: [act('costovertebral', 'depression')],
    functions: ['Depress the ribs during forced expiration'],
    reviewStatus: 'draft',
  },
  {
    id: 'innermost_intercostal', name: 'Innermost intercostals',
    latin: 'Musculi intercostales intimi', region: 'thorax', group: 'respiratory',
    origin: [at('rib_inner')], insertion: [at('rib_inner')],
    innervation: [inn('intercostal', ['T1', 'T2', 'T3', 'T4', 'T5', 'T6',
                                      'T7', 'T8', 'T9', 'T10', 'T11'])],
    actions: [act('costovertebral', 'depression', 'assist')],
    notes: 'The neurovascular bundle runs between the internal and innermost layers.',
    reviewStatus: 'draft',
  },
  {
    id: 'transversus_thoracis', name: 'Transversus thoracis',
    latin: 'Musculus transversus thoracis', region: 'thorax', group: 'respiratory',
    origin: [at('sternum_body', 'posterior surface'), at('xiphoid_process')],
    insertion: [at('costal_cartilages', 'ribs 2–6')],
    innervation: [inn('intercostal', ['T2', 'T3', 'T4', 'T5', 'T6'])],
    actions: [act('costovertebral', 'depression', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'levatores_costarum', name: 'Levatores costarum',
    latin: 'Musculi levatores costarum', region: 'thorax', group: 'respiratory',
    origin: [at('thoracic_transverse', 'C7–T11')], insertion: [at('rib_borders')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('costovertebral', 'elevation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'serratus_posterior_superior', name: 'Serratus posterior superior',
    latin: 'Musculus serratus posterior superior', region: 'back', group: 'respiratory',
    origin: [at('nuchal_ligament'), at('c7_t12_spinous', 'C7–T3')],
    insertion: [at('rib_borders', 'ribs 2–5')],
    innervation: [inn('intercostal', ['T2', 'T3', 'T4', 'T5'])],
    actions: [act('costovertebral', 'elevation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'serratus_posterior_inferior', name: 'Serratus posterior inferior',
    latin: 'Musculus serratus posterior inferior', region: 'back', group: 'respiratory',
    origin: [at('t7_l5_spinous', 'T11–L2')], insertion: [at('rib_borders', 'ribs 9–12')],
    innervation: [inn('intercostal', ['T9', 'T10', 'T11']), inn('subcostal', ['T12'])],
    actions: [act('costovertebral', 'depression', 'assist')],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------- deep transversospinalis */
  {
    id: 'semispinalis_cervicis', name: 'Semispinalis cervicis',
    latin: 'Musculus semispinalis cervicis', region: 'back', group: 'transversospinalis',
    trainableUnitId: 'neck_extensors',
    origin: [at('c7_t6_transverse', 'T1–T6')], insertion: [at('c2_c4_spinous')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('cervical_spine_joint', 'extension'),
              act('cervical_spine_joint', 'rotation', 'assist', 'contralateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'semispinalis_thoracis', name: 'Semispinalis thoracis',
    latin: 'Musculus semispinalis thoracis', region: 'back', group: 'transversospinalis',
    trainableUnitId: 'erectors',
    origin: [at('thoracic_transverse', 'T6–T10')], insertion: [at('t3_t6_spinous', 'C6–T4')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension'), act('spine', 'rotation', 'assist', 'contralateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'rotatores', name: 'Rotatores', latin: 'Musculi rotatores', region: 'back',
    group: 'transversospinalis', trainableUnitId: 'deep_core',
    origin: [at('thoracic_transverse')],
    insertion: [at('spinous_processes_general', 'one to two levels above')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'rotation', 'assist', 'contralateral'),
              act('spine', 'extension', 'stabilize')],
    notes: 'The deepest and shortest of the transversospinalis group; densely '
         + 'supplied with muscle spindles, suggesting a proprioceptive role.',
    reviewStatus: 'draft',
  },
  {
    id: 'interspinales', name: 'Interspinales', latin: 'Musculi interspinales', region: 'back',
    group: 'deep back', trainableUnitId: 'deep_core',
    origin: [at('spinous_adjacent')], insertion: [at('spinous_adjacent')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'extension', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'intertransversarii', name: 'Intertransversarii',
    latin: 'Musculi intertransversarii', region: 'back', group: 'deep back',
    trainableUnitId: 'deep_core',
    origin: [at('transverse_adjacent')], insertion: [at('transverse_adjacent')],
    innervation: [inn('dorsal_rami_spinal', ['C1–S5'])],
    actions: [act('spine', 'lateral_flexion', 'assist', 'ipsilateral')],
    reviewStatus: 'draft',
  },

  /* ----------------------------------------------------------- pelvic floor */
  {
    id: 'pubococcygeus', name: 'Pubococcygeus', latin: 'Musculus pubococcygeus',
    region: 'perineum', group: 'levator ani',
    origin: [at('pubis_inner')], insertion: [at('coccyx_body'), at('anococcygeal_ligament')],
    innervation: [inn('sacral_rami', ['S3', 'S4']), inn('pudendal', ['S2', 'S3', 'S4'])],
    actions: [], functions: ['Supports the pelvic viscera', 'Maintains continence'],
    reviewStatus: 'draft',
  },
  {
    id: 'puborectalis', name: 'Puborectalis', latin: 'Musculus puborectalis',
    region: 'perineum', group: 'levator ani',
    origin: [at('pubis_inner')], insertion: [at('perineal_body', 'slings around the anorectal junction')],
    innervation: [inn('sacral_rami', ['S3', 'S4']), inn('pudendal', ['S2', 'S3', 'S4'])],
    actions: [],
    functions: ['Maintains the anorectal angle, central to faecal continence',
                'Relaxes to allow defecation'],
    reviewStatus: 'draft',
  },
  {
    id: 'iliococcygeus', name: 'Iliococcygeus', latin: 'Musculus iliococcygeus',
    region: 'perineum', group: 'levator ani',
    origin: [at('tendinous_arch_levator'), at('ischial_spine')],
    insertion: [at('anococcygeal_ligament')],
    innervation: [inn('sacral_rami', ['S3', 'S4']), inn('pudendal', ['S2', 'S3', 'S4'])],
    actions: [], functions: ['Forms the bulk of the pelvic diaphragm'],
    reviewStatus: 'draft',
  },
  {
    id: 'coccygeus', name: 'Coccygeus', latin: 'Musculus coccygeus',
    region: 'perineum', group: 'pelvic diaphragm',
    origin: [at('ischial_spine')], insertion: [at('sacrum_posterior'), at('anococcygeal_ligament')],
    innervation: [inn('sacral_rami', ['S3', 'S4'])],
    actions: [], functions: ['Supports the pelvic viscera', 'Flexes the coccyx'],
    reviewStatus: 'draft',
  },
]
