/** Head and neck: mastication, facial expression, the extraocular muscles, the
 *  hyoid groups, the suboccipital triangle and the prevertebral muscles.
 *  Nothing here carries a trainableUnitId. */

import type { AnatomicalMuscle } from '../taxonomy/anatomy'
import { at, act, inn } from './helpers'

export const HEAD_NECK_MUSCLES: AnatomicalMuscle[] = [
  /* ------------------------------------------------------------ mastication */
  {
    id: 'masseter', name: 'Masseter', latin: 'Musculus masseter',
    region: 'head', group: 'muscles of mastication', palpable: true,
    origin: [at('zygomatic_arch')],
    insertion: [at('mandible_angle'), at('mandible_ramus', 'lateral surface')],
    innervation: [inn('mandibular_v3', ['CN V3'], 'masseteric nerve')],
    actions: [act('temporomandibular', 'elevation'),
              act('temporomandibular', 'protraction', 'assist')],
    notes: 'The strongest muscle in the body by force per cross-sectional area.',
    reviewStatus: 'draft',
  },
  {
    id: 'temporalis', name: 'Temporalis', latin: 'Musculus temporalis',
    region: 'head', group: 'muscles of mastication', palpable: true,
    origin: [at('temporal_fossa')],
    insertion: [at('mandible_coronoid'), at('mandible_ramus', 'anterior border')],
    innervation: [inn('mandibular_v3', ['CN V3'], 'deep temporal nerves')],
    actions: [act('temporomandibular', 'elevation'),
              act('temporomandibular', 'retraction', 'prime', 'posterior fibres')],
    reviewStatus: 'draft',
  },
  {
    id: 'medial_pterygoid', name: 'Medial pterygoid', latin: 'Musculus pterygoideus medialis',
    region: 'head', group: 'muscles of mastication',
    origin: [at('lateral_pterygoid_plate', 'medial surface'), at('maxilla_alveolar')],
    insertion: [at('mandible_angle', 'medial surface'), at('mandible_ramus', 'medial surface')],
    innervation: [inn('mandibular_v3', ['CN V3'])],
    actions: [act('temporomandibular', 'elevation'),
              act('temporomandibular', 'protraction', 'assist'),
              act('temporomandibular', 'rotation', 'assist', 'contralateral grinding')],
    reviewStatus: 'draft',
  },
  {
    id: 'lateral_pterygoid', name: 'Lateral pterygoid', latin: 'Musculus pterygoideus lateralis',
    region: 'head', group: 'muscles of mastication',
    origin: [at('sphenoid_greater_wing', 'upper head'),
             at('lateral_pterygoid_plate', 'lower head, lateral surface')],
    insertion: [at('mandible_condyle')],
    innervation: [inn('mandibular_v3', ['CN V3'])],
    actions: [act('temporomandibular', 'protraction'),
              act('temporomandibular', 'depression', 'prime', 'opens the jaw'),
              act('temporomandibular', 'rotation', 'prime', 'contralateral')],
    notes: 'The only muscle of mastication that opens the jaw.',
    reviewStatus: 'draft',
  },

  /* ---------------------------------------------------- facial expression */
  {
    id: 'occipitofrontalis', name: 'Occipitofrontalis', latin: 'Musculus occipitofrontalis',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('nuchal_line_superior', 'occipital belly'), at('galea_aponeurotica')],
    insertion: [at('facial_skin', 'skin of the eyebrows and forehead')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Raises the eyebrows', 'Wrinkles the forehead'],
    reviewStatus: 'draft',
  },
  {
    id: 'orbicularis_oculi', name: 'Orbicularis oculi', latin: 'Musculus orbicularis oculi',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('medial_palpebral_ligament'), at('medial_palpebral_ligament', 'and the medial orbital margin')],
    insertion: [at('facial_skin', 'skin around the orbit and the eyelids')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [],
    functions: ['Closes the eyelids (palpebral part, gentle blink)',
                'Forcefully closes the eye (orbital part)',
                'Drains tears via the lacrimal part'],
    notes: 'Facial nerve palsy prevents eye closure, risking corneal exposure.',
    reviewStatus: 'draft',
  },
  {
    id: 'orbicularis_oris', name: 'Orbicularis oris', latin: 'Musculus orbicularis oris',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('maxilla_alveolar'), at('mandible_alveolar')],
    insertion: [at('facial_skin', 'skin and mucosa of the lips')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Closes and purses the lips', 'Required for whistling and speech'],
    reviewStatus: 'draft',
  },
  {
    id: 'buccinator', name: 'Buccinator', latin: 'Musculus buccinator',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('maxilla_alveolar'), at('mandible_alveolar'), at('pterygomandibular_raphe')],
    insertion: [at('facial_skin', 'blends into orbicularis oris at the angle of the mouth')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [],
    functions: ['Presses the cheek against the teeth, keeping food on the occlusal surface',
                'Compresses the cheek when blowing'],
    notes: 'A muscle of facial expression, not of mastication, despite its role in chewing.',
    reviewStatus: 'draft',
  },
  {
    id: 'zygomaticus_major', name: 'Zygomaticus major', latin: 'Musculus zygomaticus major',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('zygomatic_arch')],
    insertion: [at('facial_skin', 'angle of the mouth')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Draws the angle of the mouth up and back — smiling'],
    reviewStatus: 'draft',
  },
  {
    id: 'levator_labii_superioris', name: 'Levator labii superioris',
    latin: 'Musculus levator labii superioris',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('maxilla_alveolar', 'infraorbital margin')],
    insertion: [at('facial_skin', 'upper lip')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Elevates the upper lip', 'Contributes to a sneer'],
    reviewStatus: 'draft',
  },
  {
    id: 'depressor_anguli_oris', name: 'Depressor anguli oris',
    latin: 'Musculus depressor anguli oris',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('mandible_body', 'oblique line')],
    insertion: [at('facial_skin', 'angle of the mouth')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Draws the angle of the mouth down — frowning'],
    reviewStatus: 'draft',
  },
  {
    id: 'mentalis', name: 'Mentalis', latin: 'Musculus mentalis',
    region: 'head', group: 'muscles of facial expression',
    origin: [at('mandible_body', 'incisive fossa')],
    insertion: [at('facial_skin', 'skin of the chin')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Protrudes the lower lip', 'Wrinkles the chin — pouting'],
    reviewStatus: 'draft',
  },
  {
    id: 'platysma', name: 'Platysma', latin: 'Musculus platysma',
    region: 'neck', group: 'muscles of facial expression',
    origin: [at('facial_skin', 'fascia over pectoralis major and deltoid')],
    insertion: [at('mandible_body', 'inferior border'), at('facial_skin', 'lower face')],
    innervation: [inn('facial', ['CN VII'], 'cervical branch')],
    actions: [], functions: ['Tenses the skin of the neck', 'Draws the corners of the mouth down'],
    reviewStatus: 'draft',
  },

  /* ------------------------------------------------------------ extraocular */
  {
    id: 'superior_rectus', name: 'Superior rectus', latin: 'Musculus rectus superior',
    region: 'head', group: 'extraocular',
    origin: [at('common_tendinous_ring')], insertion: [at('sclera', 'superior surface')],
    innervation: [inn('oculomotor', ['CN III'])],
    actions: [act('eye', 'elevation'), act('eye', 'adduction', 'assist'),
              act('eye', 'internal_rotation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'inferior_rectus', name: 'Inferior rectus', latin: 'Musculus rectus inferior',
    region: 'head', group: 'extraocular',
    origin: [at('common_tendinous_ring')], insertion: [at('sclera', 'inferior surface')],
    innervation: [inn('oculomotor', ['CN III'])],
    actions: [act('eye', 'depression'), act('eye', 'adduction', 'assist'),
              act('eye', 'external_rotation', 'assist')],
    reviewStatus: 'draft',
  },
  {
    id: 'medial_rectus', name: 'Medial rectus', latin: 'Musculus rectus medialis',
    region: 'head', group: 'extraocular',
    origin: [at('common_tendinous_ring')], insertion: [at('sclera', 'medial surface')],
    innervation: [inn('oculomotor', ['CN III'])],
    actions: [act('eye', 'adduction')],
    reviewStatus: 'draft',
  },
  {
    id: 'lateral_rectus', name: 'Lateral rectus', latin: 'Musculus rectus lateralis',
    region: 'head', group: 'extraocular',
    origin: [at('common_tendinous_ring')], insertion: [at('sclera', 'lateral surface')],
    innervation: [inn('abducens', ['CN VI'])],
    actions: [act('eye', 'abduction')],
    notes: 'LR6 — the lateral rectus is the CN VI muscle.',
    reviewStatus: 'draft',
  },
  {
    id: 'superior_oblique', name: 'Superior oblique', latin: 'Musculus obliquus superior',
    region: 'head', group: 'extraocular',
    origin: [at('sphenoid_greater_wing', 'body of the sphenoid, above the ring')],
    insertion: [at('sclera', 'superolateral, via the trochlea')],
    innervation: [inn('trochlear', ['CN IV'])],
    actions: [act('eye', 'depression', 'prime', 'when adducted'),
              act('eye', 'abduction', 'assist'), act('eye', 'internal_rotation')],
    notes: 'SO4 — the superior oblique is the CN IV muscle; it is the only one using a pulley.',
    reviewStatus: 'draft',
  },
  {
    id: 'inferior_oblique', name: 'Inferior oblique', latin: 'Musculus obliquus inferior',
    region: 'head', group: 'extraocular',
    origin: [at('maxilla_alveolar', 'orbital floor')], insertion: [at('sclera', 'inferolateral')],
    innervation: [inn('oculomotor', ['CN III'])],
    actions: [act('eye', 'elevation', 'prime', 'when adducted'),
              act('eye', 'abduction', 'assist'), act('eye', 'external_rotation')],
    reviewStatus: 'draft',
  },
  {
    id: 'levator_palpebrae_superioris', name: 'Levator palpebrae superioris',
    latin: 'Musculus levator palpebrae superioris', region: 'head', group: 'extraocular',
    origin: [at('sphenoid_greater_wing', 'above the optic canal')], insertion: [at('tarsal_plate')],
    innervation: [inn('oculomotor', ['CN III'])],
    actions: [], functions: ['Raises the upper eyelid'],
    notes: 'Its paralysis gives ptosis, a sign of CN III palsy or Horner syndrome.',
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------------- suprahyoid */
  {
    id: 'digastric', name: 'Digastric', latin: 'Musculus digastricus',
    region: 'neck', group: 'suprahyoid',
    origin: [at('mastoid_notch', 'posterior belly'), at('digastric_fossa', 'anterior belly')],
    insertion: [at('hyoid_body', 'via an intermediate tendon')],
    innervation: [inn('facial', ['CN VII'], 'posterior belly'),
                  inn('mandibular_v3', ['CN V3'], 'anterior belly, via the mylohyoid nerve')],
    actions: [act('temporomandibular', 'depression', 'assist')],
    functions: ['Elevates the hyoid during swallowing'],
    notes: 'Two bellies with different embryological origins and different nerves.',
    reviewStatus: 'draft',
  },
  {
    id: 'mylohyoid', name: 'Mylohyoid', latin: 'Musculus mylohyoideus',
    region: 'neck', group: 'suprahyoid',
    origin: [at('mylohyoid_line')], insertion: [at('hyoid_body')],
    innervation: [inn('mandibular_v3', ['CN V3'])],
    actions: [], functions: ['Forms the floor of the mouth', 'Elevates the hyoid and tongue'],
    reviewStatus: 'draft',
  },
  {
    id: 'geniohyoid', name: 'Geniohyoid', latin: 'Musculus geniohyoideus',
    region: 'neck', group: 'suprahyoid',
    origin: [at('mental_spine')], insertion: [at('hyoid_body')],
    innervation: [inn('c1_via_hypoglossal', ['C1'])],
    actions: [], functions: ['Draws the hyoid up and forward'],
    reviewStatus: 'draft',
  },
  {
    id: 'stylohyoid', name: 'Stylohyoid', latin: 'Musculus stylohyoideus',
    region: 'neck', group: 'suprahyoid',
    origin: [at('styloid_process_temporal')], insertion: [at('hyoid_body')],
    innervation: [inn('facial', ['CN VII'])],
    actions: [], functions: ['Draws the hyoid up and back'],
    reviewStatus: 'draft',
  },

  /* -------------------------------------------------------------- infrahyoid */
  {
    id: 'sternohyoid', name: 'Sternohyoid', latin: 'Musculus sternohyoideus',
    region: 'neck', group: 'infrahyoid',
    origin: [at('manubrium_posterior'), at('clavicle_medial')], insertion: [at('hyoid_body')],
    innervation: [inn('ansa_cervicalis', ['C1', 'C2', 'C3'])],
    actions: [], functions: ['Depresses the hyoid after swallowing'],
    reviewStatus: 'draft',
  },
  {
    id: 'sternothyroid', name: 'Sternothyroid', latin: 'Musculus sternothyroideus',
    region: 'neck', group: 'infrahyoid',
    origin: [at('manubrium_posterior')], insertion: [at('thyroid_cartilage')],
    innervation: [inn('ansa_cervicalis', ['C1', 'C2', 'C3'])],
    actions: [], functions: ['Depresses the larynx'],
    reviewStatus: 'draft',
  },
  {
    id: 'thyrohyoid', name: 'Thyrohyoid', latin: 'Musculus thyrohyoideus',
    region: 'neck', group: 'infrahyoid',
    origin: [at('thyroid_cartilage')], insertion: [at('hyoid_body')],
    innervation: [inn('c1_via_hypoglossal', ['C1'])],
    actions: [], functions: ['Depresses the hyoid, or elevates the larynx when the hyoid is fixed'],
    reviewStatus: 'draft',
  },
  {
    id: 'omohyoid', name: 'Omohyoid', latin: 'Musculus omohyoideus',
    region: 'neck', group: 'infrahyoid',
    origin: [at('scapula_superior_border')], insertion: [at('hyoid_body')],
    innervation: [inn('ansa_cervicalis', ['C1', 'C2', 'C3'])],
    actions: [], functions: ['Depresses the hyoid'],
    notes: 'Two bellies joined by an intermediate tendon; divides the posterior triangle.',
    reviewStatus: 'draft',
  },

  /* ---------------------------------------------------------- suboccipital */
  {
    id: 'rectus_capitis_posterior_major', name: 'Rectus capitis posterior major',
    latin: 'Musculus rectus capitis posterior major', region: 'neck', group: 'suboccipital',
    origin: [at('axis_spinous')], insertion: [at('nuchal_line_inferior', 'lateral part')],
    innervation: [inn('suboccipital', ['C1'])],
    actions: [act('atlanto_occipital', 'extension'),
              act('atlanto_axial', 'rotation', 'prime', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'rectus_capitis_posterior_minor', name: 'Rectus capitis posterior minor',
    latin: 'Musculus rectus capitis posterior minor', region: 'neck', group: 'suboccipital',
    origin: [at('atlas_posterior_tubercle')], insertion: [at('nuchal_line_inferior', 'medial part')],
    innervation: [inn('suboccipital', ['C1'])],
    actions: [act('atlanto_occipital', 'extension')],
    reviewStatus: 'draft',
  },
  {
    id: 'obliquus_capitis_superior', name: 'Obliquus capitis superior',
    latin: 'Musculus obliquus capitis superior', region: 'neck', group: 'suboccipital',
    origin: [at('atlas_transverse')], insertion: [at('occipital_between_nuchal_lines')],
    innervation: [inn('suboccipital', ['C1'])],
    actions: [act('atlanto_occipital', 'extension'),
              act('atlanto_occipital', 'lateral_flexion', 'assist', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'obliquus_capitis_inferior', name: 'Obliquus capitis inferior',
    latin: 'Musculus obliquus capitis inferior', region: 'neck', group: 'suboccipital',
    origin: [at('axis_spinous')], insertion: [at('atlas_transverse')],
    innervation: [inn('suboccipital', ['C1'])],
    actions: [act('atlanto_axial', 'rotation', 'prime', 'ipsilateral')],
    notes: 'The only suboccipital muscle attaching to no part of the skull.',
    reviewStatus: 'draft',
  },

  /* --------------------------------------------------------- prevertebral */
  {
    id: 'longus_colli', name: 'Longus colli', latin: 'Musculus longus colli',
    region: 'neck', group: 'prevertebral', trainableUnitId: 'neck_flexors',
    origin: [at('cervical_bodies_c3_t3')],
    insertion: [at('atlas_anterior_tubercle'), at('c3_c6_transverse')],
    innervation: [inn('cervical_rami', ['C2', 'C3', 'C4', 'C5'])],
    actions: [act('cervical_spine_joint', 'flexion'),
              act('cervical_spine_joint', 'lateral_flexion', 'assist', 'ipsilateral')],
    reviewStatus: 'draft',
  },
  {
    id: 'longus_capitis', name: 'Longus capitis', latin: 'Musculus longus capitis',
    region: 'neck', group: 'prevertebral', trainableUnitId: 'neck_flexors',
    origin: [at('c3_c6_transverse')], insertion: [at('basilar_occipital')],
    innervation: [inn('cervical_rami', ['C1', 'C2', 'C3'])],
    actions: [act('atlanto_occipital', 'flexion')],
    reviewStatus: 'draft',
  },
  {
    id: 'rectus_capitis_anterior', name: 'Rectus capitis anterior',
    latin: 'Musculus rectus capitis anterior', region: 'neck', group: 'prevertebral',
    trainableUnitId: 'neck_flexors',
    origin: [at('atlas_lateral_mass')], insertion: [at('basilar_occipital')],
    innervation: [inn('cervical_rami', ['C1', 'C2'])],
    actions: [act('atlanto_occipital', 'flexion')],
    reviewStatus: 'draft',
  },
]
