/** Peripheral nerves, as a hierarchy so a card can ask about a named nerve or
 *  about the cord/plexus above it. Root levels are stored per muscle as well as
 *  per nerve, because a muscle often draws on a subset of its nerve's roots. */

import type { Nerve } from '../taxonomy/anatomy'

export const NERVES: Nerve[] = [
  // --- brachial plexus
  { id: 'brachial_plexus', name: 'Brachial plexus', plexus: 'brachial',
    roots: ['C5', 'C6', 'C7', 'C8', 'T1'] },
  { id: 'dorsal_scapular', name: 'Dorsal scapular nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C4', 'C5'] },
  { id: 'long_thoracic', name: 'Long thoracic nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6', 'C7'] },
  { id: 'suprascapular', name: 'Suprascapular nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6'] },
  { id: 'lateral_pectoral', name: 'Lateral pectoral nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6', 'C7'] },
  { id: 'medial_pectoral', name: 'Medial pectoral nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C8', 'T1'] },
  { id: 'upper_subscapular', name: 'Upper subscapular nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6'] },
  { id: 'lower_subscapular', name: 'Lower subscapular nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6'] },
  { id: 'thoracodorsal', name: 'Thoracodorsal nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C6', 'C7', 'C8'] },
  { id: 'axillary', name: 'Axillary nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6'] },
  { id: 'musculocutaneous', name: 'Musculocutaneous nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6', 'C7'] },
  { id: 'radial', name: 'Radial nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C5', 'C6', 'C7', 'C8', 'T1'] },
  { id: 'posterior_interosseous', name: 'Posterior interosseous nerve', plexus: 'brachial',
    parentId: 'radial', roots: ['C7', 'C8'] },
  { id: 'median', name: 'Median nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C6', 'C7', 'C8', 'T1'] },
  { id: 'anterior_interosseous', name: 'Anterior interosseous nerve', plexus: 'brachial',
    parentId: 'median', roots: ['C7', 'C8'] },
  { id: 'ulnar', name: 'Ulnar nerve', plexus: 'brachial',
    parentId: 'brachial_plexus', roots: ['C8', 'T1'] },

  // --- cervical
  { id: 'accessory', name: 'Accessory nerve (CN XI)', plexus: 'none', roots: ['CN XI'] },
  { id: 'cervical_plexus', name: 'Cervical plexus', plexus: 'cervical',
    roots: ['C1', 'C2', 'C3', 'C4'] },
  { id: 'cervical_rami', name: 'Cervical spinal nerves (anterior rami)', plexus: 'cervical',
    parentId: 'cervical_plexus', roots: ['C3', 'C4', 'C5'] },
  { id: 'dorsal_rami_cervical', name: 'Cervical dorsal rami', plexus: 'none',
    roots: ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8'] },
  { id: 'dorsal_rami_spinal', name: 'Spinal dorsal rami', plexus: 'none', roots: ['C1–S5'] },

  // --- trunk
  { id: 'intercostal', name: 'Intercostal nerves', plexus: 'none',
    roots: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11'] },
  { id: 'thoracoabdominal', name: 'Thoracoabdominal nerves', plexus: 'none',
    parentId: 'intercostal', roots: ['T7', 'T8', 'T9', 'T10', 'T11'] },
  { id: 'subcostal', name: 'Subcostal nerve', plexus: 'none', roots: ['T12'] },
  { id: 'iliohypogastric', name: 'Iliohypogastric nerve', plexus: 'lumbar', roots: ['L1'] },
  { id: 'ilioinguinal', name: 'Ilioinguinal nerve', plexus: 'lumbar', roots: ['L1'] },

  // --- lumbosacral plexus
  { id: 'lumbar_plexus', name: 'Lumbar plexus', plexus: 'lumbar',
    roots: ['L1', 'L2', 'L3', 'L4'] },
  { id: 'lumbar_rami', name: 'Lumbar spinal nerves (anterior rami)', plexus: 'lumbar',
    parentId: 'lumbar_plexus', roots: ['L1', 'L2', 'L3', 'L4'] },
  { id: 'femoral', name: 'Femoral nerve', plexus: 'lumbar',
    parentId: 'lumbar_plexus', roots: ['L2', 'L3', 'L4'] },
  { id: 'obturator', name: 'Obturator nerve', plexus: 'lumbar',
    parentId: 'lumbar_plexus', roots: ['L2', 'L3', 'L4'] },
  { id: 'sacral_plexus', name: 'Sacral plexus', plexus: 'sacral',
    roots: ['L4', 'L5', 'S1', 'S2', 'S3'] },
  { id: 'superior_gluteal', name: 'Superior gluteal nerve', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['L4', 'L5', 'S1'] },
  { id: 'inferior_gluteal', name: 'Inferior gluteal nerve', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['L5', 'S1', 'S2'] },
  { id: 'sciatic', name: 'Sciatic nerve', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['L4', 'L5', 'S1', 'S2', 'S3'] },
  { id: 'tibial', name: 'Tibial nerve', plexus: 'sacral',
    parentId: 'sciatic', roots: ['L4', 'L5', 'S1', 'S2', 'S3'] },
  { id: 'common_fibular', name: 'Common fibular nerve', plexus: 'sacral',
    parentId: 'sciatic', roots: ['L4', 'L5', 'S1', 'S2'] },
  { id: 'deep_fibular', name: 'Deep fibular nerve', plexus: 'sacral',
    parentId: 'common_fibular', roots: ['L4', 'L5', 'S1'] },
  { id: 'superficial_fibular', name: 'Superficial fibular nerve', plexus: 'sacral',
    parentId: 'common_fibular', roots: ['L5', 'S1', 'S2'] },
  { id: 'nerve_to_piriformis', name: 'Nerve to piriformis', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['S1', 'S2'] },
  { id: 'nerve_to_obturator_internus', name: 'Nerve to obturator internus', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['L5', 'S1', 'S2'] },
  { id: 'nerve_to_quadratus_femoris', name: 'Nerve to quadratus femoris', plexus: 'sacral',
    parentId: 'sacral_plexus', roots: ['L4', 'L5', 'S1'] },
]
