/** Bones, bony landmarks and joints. Landmarks are the nodes muscle attachments
 *  point at, which is what turns origin/insertion prose into a traversable
 *  graph. See docs/anatomy-model.md §2 */

import type { Bone, Landmark, Joint } from '../taxonomy/anatomy'

export const BONES: Bone[] = [
  { id: 'skull',      name: 'Skull',      region: 'axial' },
  { id: 'mandible',   name: 'Mandible',   region: 'axial' },
  { id: 'cervical_spine', name: 'Cervical vertebrae', region: 'axial' },
  { id: 'thoracic_spine', name: 'Thoracic vertebrae', region: 'axial' },
  { id: 'lumbar_spine',   name: 'Lumbar vertebrae',   region: 'axial' },
  { id: 'sacrum',     name: 'Sacrum',     region: 'axial' },
  { id: 'coccyx',     name: 'Coccyx',     region: 'axial' },
  { id: 'ribs',       name: 'Ribs',       region: 'axial' },
  { id: 'sternum',    name: 'Sternum',    region: 'axial' },
  { id: 'clavicle',   name: 'Clavicle',   region: 'girdle' },
  { id: 'scapula',    name: 'Scapula',    region: 'girdle' },
  { id: 'humerus',    name: 'Humerus',    region: 'arms' },
  { id: 'radius',     name: 'Radius',     region: 'arms' },
  { id: 'ulna',       name: 'Ulna',       region: 'arms' },
  { id: 'carpals',    name: 'Carpal bones', region: 'arms' },
  { id: 'metacarpals', name: 'Metacarpals', region: 'arms' },
  { id: 'phalanges_hand', name: 'Phalanges (hand)', region: 'arms' },
  { id: 'ilium',      name: 'Ilium',      region: 'legs' },
  { id: 'ischium',    name: 'Ischium',    region: 'legs' },
  { id: 'pubis',      name: 'Pubis',      region: 'legs' },
  { id: 'femur',      name: 'Femur',      region: 'legs' },
  { id: 'patella',    name: 'Patella',    region: 'legs' },
  { id: 'tibia',      name: 'Tibia',      region: 'legs' },
  { id: 'fibula',     name: 'Fibula',     region: 'legs' },
  { id: 'tarsals',    name: 'Tarsal bones', region: 'legs' },
  { id: 'metatarsals', name: 'Metatarsals', region: 'legs' },
  { id: 'phalanges_foot', name: 'Phalanges (foot)', region: 'legs' },
]

const L = (id: string, name: string, boneId: string): Landmark => ({ id, name, boneId })

export const LANDMARKS: Landmark[] = [
  // skull / spine
  L('nuchal_line_superior', 'Superior nuchal line', 'skull'),
  L('external_occipital_protuberance', 'External occipital protuberance', 'skull'),
  L('mastoid_process', 'Mastoid process', 'skull'),
  L('nuchal_ligament', 'Nuchal ligament', 'cervical_spine'),
  L('c1_c4_transverse', 'Transverse processes of C1–C4', 'cervical_spine'),
  L('cervical_spinous', 'Cervical spinous processes', 'cervical_spine'),
  L('c7_t12_spinous', 'Spinous processes of C7–T12', 'thoracic_spine'),
  L('t1_t3_spinous', 'Spinous processes of T1–T3', 'thoracic_spine'),
  L('t7_l5_spinous', 'Spinous processes of T7–L5', 'thoracic_spine'),
  L('lumbar_transverse', 'Lumbar transverse processes', 'lumbar_spine'),
  L('lumbar_bodies', 'Lumbar vertebral bodies', 'lumbar_spine'),
  L('thoracolumbar_fascia', 'Thoracolumbar fascia', 'lumbar_spine'),
  L('sacrum_posterior', 'Posterior sacrum', 'sacrum'),
  L('sacrum_anterior', 'Anterior sacrum', 'sacrum'),
  // thorax
  L('ribs_1_8_lateral', 'Lateral surface of ribs 1–8', 'ribs'),
  L('ribs_3_5', 'Ribs 3–5', 'ribs'),
  L('ribs_lower', 'Lower ribs (5–12)', 'ribs'),
  L('rib_1', 'First rib', 'ribs'),
  L('costal_cartilages', 'Costal cartilages', 'ribs'),
  L('sternum_body', 'Body of the sternum', 'sternum'),
  L('xiphoid_process', 'Xiphoid process', 'sternum'),
  L('manubrium', 'Manubrium', 'sternum'),
  // clavicle & scapula
  L('clavicle_medial', 'Medial third of the clavicle', 'clavicle'),
  L('clavicle_lateral', 'Lateral third of the clavicle', 'clavicle'),
  L('acromion', 'Acromion', 'scapula'),
  L('scapular_spine', 'Spine of the scapula', 'scapula'),
  L('coracoid_process', 'Coracoid process', 'scapula'),
  L('supraglenoid_tubercle', 'Supraglenoid tubercle', 'scapula'),
  L('infraglenoid_tubercle', 'Infraglenoid tubercle', 'scapula'),
  L('supraspinous_fossa', 'Supraspinous fossa', 'scapula'),
  L('infraspinous_fossa', 'Infraspinous fossa', 'scapula'),
  L('subscapular_fossa', 'Subscapular fossa', 'scapula'),
  L('scapula_medial_border', 'Medial border of the scapula', 'scapula'),
  L('scapula_lateral_border', 'Lateral border of the scapula', 'scapula'),
  L('scapula_inferior_angle', 'Inferior angle of the scapula', 'scapula'),
  L('scapula_superior_angle', 'Superior angle of the scapula', 'scapula'),
  // humerus
  L('greater_tubercle', 'Greater tubercle of the humerus', 'humerus'),
  L('lesser_tubercle', 'Lesser tubercle of the humerus', 'humerus'),
  L('intertubercular_groove_lateral', 'Lateral lip of the intertubercular groove', 'humerus'),
  L('intertubercular_groove_medial', 'Medial lip of the intertubercular groove', 'humerus'),
  L('intertubercular_groove_floor', 'Floor of the intertubercular groove', 'humerus'),
  L('deltoid_tuberosity', 'Deltoid tuberosity', 'humerus'),
  L('humerus_shaft_medial', 'Medial humeral shaft', 'humerus'),
  L('humerus_shaft_posterior', 'Posterior humeral shaft', 'humerus'),
  L('medial_epicondyle', 'Medial epicondyle of the humerus', 'humerus'),
  L('lateral_epicondyle', 'Lateral epicondyle of the humerus', 'humerus'),
  L('lateral_supracondylar_ridge', 'Lateral supracondylar ridge', 'humerus'),
  // forearm & hand
  L('radial_tuberosity', 'Radial tuberosity', 'radius'),
  L('radius_shaft', 'Shaft of the radius', 'radius'),
  L('radius_styloid', 'Styloid process of the radius', 'radius'),
  L('olecranon', 'Olecranon', 'ulna'),
  L('ulna_shaft', 'Shaft of the ulna', 'ulna'),
  L('ulna_coronoid', 'Coronoid process of the ulna', 'ulna'),
  L('pisiform', 'Pisiform', 'carpals'),
  L('metacarpal_2_3_base', 'Base of the 2nd and 3rd metacarpals', 'metacarpals'),
  L('metacarpal_5_base', 'Base of the 5th metacarpal', 'metacarpals'),
  L('metacarpal_1_base', 'Base of the 1st metacarpal', 'metacarpals'),
  L('phalanges_middle', 'Middle phalanges', 'phalanges_hand'),
  L('phalanges_distal_hand', 'Distal phalanges', 'phalanges_hand'),
  L('extensor_expansion', 'Extensor expansion', 'phalanges_hand'),
  // pelvis
  L('iliac_crest', 'Iliac crest', 'ilium'),
  L('asis', 'Anterior superior iliac spine (ASIS)', 'ilium'),
  L('aiis', 'Anterior inferior iliac spine (AIIS)', 'ilium'),
  L('iliac_fossa', 'Iliac fossa', 'ilium'),
  L('gluteal_surface', 'Gluteal surface of the ilium', 'ilium'),
  L('psis', 'Posterior superior iliac spine (PSIS)', 'ilium'),
  L('ischial_tuberosity', 'Ischial tuberosity', 'ischium'),
  L('ischial_ramus', 'Ischial ramus', 'ischium'),
  L('ischial_spine', 'Ischial spine', 'ischium'),
  L('pubic_body', 'Body of the pubis', 'pubis'),
  L('pubic_ramus_inferior', 'Inferior pubic ramus', 'pubis'),
  L('pubic_ramus_superior', 'Superior pubic ramus', 'pubis'),
  L('pubic_tubercle', 'Pubic tubercle', 'pubis'),
  L('pectineal_line_pubis', 'Pectineal line of the pubis', 'pubis'),
  L('obturator_foramen', 'Margin of the obturator foramen', 'pubis'),
  // femur & knee
  L('greater_trochanter', 'Greater trochanter', 'femur'),
  L('lesser_trochanter', 'Lesser trochanter', 'femur'),
  L('gluteal_tuberosity', 'Gluteal tuberosity', 'femur'),
  L('linea_aspera', 'Linea aspera', 'femur'),
  L('femur_shaft_anterior', 'Anterior femoral shaft', 'femur'),
  L('intertrochanteric_crest', 'Intertrochanteric crest', 'femur'),
  L('femur_condyle_medial', 'Medial femoral condyle', 'femur'),
  L('femur_condyle_lateral', 'Lateral femoral condyle', 'femur'),
  L('adductor_tubercle', 'Adductor tubercle', 'femur'),
  L('patella_base', 'Base of the patella', 'patella'),
  // leg & foot
  L('tibial_tuberosity', 'Tibial tuberosity', 'tibia'),
  L('pes_anserinus', 'Pes anserinus (medial tibia)', 'tibia'),
  L('tibia_lateral_condyle', 'Lateral condyle of the tibia', 'tibia'),
  L('tibia_medial_condyle', 'Medial condyle of the tibia', 'tibia'),
  L('tibia_shaft_lateral', 'Lateral tibial shaft', 'tibia'),
  L('tibia_shaft_posterior', 'Posterior tibial shaft', 'tibia'),
  L('soleal_line', 'Soleal line of the tibia', 'tibia'),
  L('fibula_head', 'Head of the fibula', 'fibula'),
  L('fibula_shaft_lateral', 'Lateral fibular shaft', 'fibula'),
  L('fibula_shaft_posterior', 'Posterior fibular shaft', 'fibula'),
  L('interosseous_membrane_leg', 'Interosseous membrane (leg)', 'tibia'),
  L('calcaneus', 'Calcaneus', 'tarsals'),
  L('calcaneal_tendon', 'Calcaneal (Achilles) tendon', 'tarsals'),
  L('navicular', 'Navicular', 'tarsals'),
  L('medial_cuneiform', 'Medial cuneiform', 'tarsals'),
  L('metatarsal_1_base', 'Base of the 1st metatarsal', 'metatarsals'),
  L('metatarsal_5_base', 'Base of the 5th metatarsal', 'metatarsals'),
  L('phalanges_distal_foot', 'Distal phalanges (foot)', 'phalanges_foot'),
  L('hallux_distal', 'Distal phalanx of the hallux', 'phalanges_foot'),
  L('iliotibial_band', 'Iliotibial band', 'tibia'),
  L('humerus_shaft_anterior', 'Anterior distal humeral shaft', 'humerus'),
  L('supinator_crest', 'Supinator crest of the ulna', 'ulna'),
  L('hamate', 'Hamate', 'carpals'),
  L('palmar_aponeurosis', 'Palmar aponeurosis', 'carpals'),
  L('interosseous_membrane_forearm', 'Interosseous membrane (forearm)', 'ulna'),
  L('external_oblique_aponeurosis', 'Aponeurosis of external oblique', 'ribs'),
  L('linea_alba', 'Linea alba', 'ribs'),
  L('inguinal_ligament', 'Inguinal ligament', 'ilium'),
  L('pubic_crest', 'Pubic crest', 'pubis'),
  L('iliac_crest_inner', 'Inner lip of the iliac crest', 'ilium'),
  L('sacrotuberous_ligament', 'Sacrotuberous ligament', 'sacrum'),
  L('anterior_sacroiliac', 'Anterior sacrum and sacroiliac region', 'sacrum'),
  L('t1_t6_transverse', 'Transverse processes of T1–T6', 'thoracic_spine'),
  L('c4_c6_transverse', 'Transverse processes of C4–C6', 'cervical_spine'),
  L('c2_c4_spinous', 'Spinous processes of C2–C4 / ligamentum nuchae', 'cervical_spine'),
  L('t3_t6_spinous', 'Spinous processes of T3–T6', 'thoracic_spine'),
  L('ribs_lower_inner', 'Inner surface of the lower ribs', 'ribs'),
  L('rib_12', 'Twelfth rib', 'ribs'),
  L('iliolumbar_ligament', 'Iliolumbar ligament', 'ilium'),
  L('sacrum_iliac_common', 'Common tendon: sacrum, iliac crest, lumbar spinous processes', 'sacrum'),
  L('pectineal_line_femur', 'Pectineal line of the femur', 'femur'),
  L('trochanteric_fossa', 'Trochanteric fossa', 'femur'),
  L('lateral_supracondylar_line', 'Lateral supracondylar line of the femur', 'femur'),
  L('intertrochanteric_line', 'Intertrochanteric line', 'femur'),
  L('acetabulum', 'Acetabulum', 'ilium'),
  L('obturator_membrane', 'Obturator membrane', 'pubis'),
  L('cuneiforms', 'Cuneiform bones', 'tarsals'),
  L('metatarsals_2_4_base', 'Bases of the 2nd–4th metatarsals', 'metatarsals'),
  L('phalanges_middle_foot', 'Middle phalanges (foot)', 'phalanges_foot'),
  L('fibula_neck', 'Neck of the fibula', 'fibula'),
  L('ribs_5_12_outer', 'Outer surface of ribs 5–12', 'ribs'),
  L('ribs_10_12', 'Ribs 10–12', 'ribs'),
  L('costal_cartilages_5_7', 'Costal cartilages 5–7', 'ribs'),
  L('rib_2', 'Second rib', 'ribs'),
  L('occipital_between_nuchal_lines', 'Occipital bone between the nuchal lines', 'skull'),
  L('cervical_transverse_all', 'Cervical transverse processes', 'cervical_spine'),
  L('c1_c3_transverse', 'Transverse processes of C1–C3', 'cervical_spine'),
  L('c7_t6_transverse', 'Transverse processes of C7–T6', 'thoracic_spine'),
  L('thoracic_transverse', 'Thoracic transverse processes', 'thoracic_spine'),
  L('spinous_processes_general', 'Spinous processes (two to four levels above)', 'thoracic_spine'),
  L('t12_l5_bodies', 'Bodies and discs of T12–L5', 'lumbar_spine'),
  L('pubic_symphysis', 'Pubic symphysis', 'pubis'),
]

export const JOINTS: Joint[] = [
  { id: 'glenohumeral', name: 'Glenohumeral (shoulder)', type: 'ball_and_socket',
    boneIds: ['scapula', 'humerus'],
    actions: ['flexion', 'extension', 'abduction', 'adduction', 'internal_rotation',
              'external_rotation', 'horizontal_adduction', 'horizontal_abduction', 'circumduction'] },
  { id: 'scapulothoracic', name: 'Scapulothoracic', type: 'plane',
    boneIds: ['scapula', 'ribs'],
    actions: ['elevation', 'depression', 'protraction', 'retraction',
              'upward_rotation', 'downward_rotation'] },
  { id: 'elbow', name: 'Elbow', type: 'hinge',
    boneIds: ['humerus', 'ulna', 'radius'], actions: ['flexion', 'extension'] },
  { id: 'radioulnar', name: 'Radioulnar', type: 'pivot',
    boneIds: ['radius', 'ulna'], actions: ['pronation', 'supination'] },
  { id: 'wrist', name: 'Wrist', type: 'condyloid',
    boneIds: ['radius', 'carpals'],
    actions: ['flexion', 'extension', 'abduction', 'adduction'] },
  { id: 'fingers', name: 'Finger joints', type: 'hinge',
    boneIds: ['metacarpals', 'phalanges_hand'],
    actions: ['flexion', 'extension', 'abduction', 'adduction', 'opposition'] },
  { id: 'hip', name: 'Hip', type: 'ball_and_socket',
    boneIds: ['ilium', 'femur'],
    actions: ['flexion', 'extension', 'abduction', 'adduction',
              'internal_rotation', 'external_rotation', 'circumduction'] },
  { id: 'knee', name: 'Knee', type: 'hinge',
    boneIds: ['femur', 'tibia', 'patella'],
    actions: ['flexion', 'extension', 'internal_rotation', 'external_rotation'] },
  { id: 'ankle', name: 'Talocrural (ankle)', type: 'hinge',
    boneIds: ['tibia', 'fibula', 'tarsals'], actions: ['dorsiflexion', 'plantarflexion'] },
  { id: 'subtalar', name: 'Subtalar', type: 'plane',
    boneIds: ['tarsals'], actions: ['inversion', 'eversion'] },
  { id: 'toes', name: 'Toe joints', type: 'hinge',
    boneIds: ['metatarsals', 'phalanges_foot'], actions: ['flexion', 'extension'] },
  { id: 'spine', name: 'Vertebral column', type: 'cartilaginous',
    boneIds: ['cervical_spine', 'thoracic_spine', 'lumbar_spine'],
    actions: ['flexion', 'extension', 'lateral_flexion', 'rotation'] },
  { id: 'cervical_spine_joint', name: 'Cervical spine', type: 'cartilaginous',
    boneIds: ['skull', 'cervical_spine'],
    actions: ['flexion', 'extension', 'lateral_flexion', 'rotation'] },
]
