/** Bony landmarks and joints. Landmarks are the nodes muscle attachments point
 *  at, which is what turns origin/insertion prose into a traversable graph.
 *  Bones themselves live in bones.ts. See docs/anatomy-model.md §2 */

import type { Landmark, Joint, LandmarkType } from '../taxonomy/anatomy'

const L = (id: string, name: string, boneId: string | undefined,
           type: LandmarkType): Landmark =>
  boneId ? { id, name, boneId, type } : { id, name, type }

export const LANDMARKS: Landmark[] = [
  L('nuchal_line_superior', "Superior nuchal line", 'occipital', 'line'),
  L('external_occipital_protuberance', "External occipital protuberance", 'occipital', 'region'),
  L('mastoid_process', "Mastoid process", 'temporal', 'process'),
  L('nuchal_ligament', "Nuchal ligament", undefined, 'ligament'),
  L('c1_c4_transverse', "Transverse processes of C1–C4", 'cervical_vertebra', 'process'),
  L('cervical_spinous', "Cervical spinous processes", 'cervical_vertebra', 'process'),
  L('c7_t12_spinous', "Spinous processes of C7–T12", 'thoracic_vertebra', 'process'),
  L('t1_t3_spinous', "Spinous processes of T1–T3", 'thoracic_vertebra', 'process'),
  L('t7_l5_spinous', "Spinous processes of T7–L5", 'thoracic_vertebra', 'process'),
  L('lumbar_transverse', "Lumbar transverse processes", 'lumbar_vertebra', 'process'),
  L('lumbar_bodies', "Lumbar vertebral bodies", 'lumbar_vertebra', 'region'),
  L('thoracolumbar_fascia', "Thoracolumbar fascia", undefined, 'fascia'),
  L('sacrum_posterior', "Posterior sacrum", 'sacrum', 'region'),
  L('coccyx_body', "Coccyx", 'coccyx', 'surface'),
  L('sacrum_anterior', "Anterior sacrum", 'sacrum', 'region'),
  L('ribs_1_8_lateral', "Lateral surface of ribs 1–8", 'rib', 'surface'),
  L('ribs_3_5', "Ribs 3–5", 'rib', 'region'),
  L('ribs_lower', "Lower ribs (5–12)", 'rib', 'region'),
  L('rib_1', "First rib", 'rib', 'region'),
  L('costal_cartilages', "Costal cartilages", undefined, 'region'),
  L('sternum_body', "Body of the sternum", 'sternum', 'region'),
  L('xiphoid_process', "Xiphoid process", 'sternum', 'process'),
  L('manubrium', "Manubrium", 'sternum', 'region'),
  L('clavicle_medial', "Medial third of the clavicle", 'clavicle', 'region'),
  L('clavicle_lateral', "Lateral third of the clavicle", 'clavicle', 'region'),
  L('acromion', "Acromion", 'scapula', 'region'),
  L('scapular_spine', "Spine of the scapula", 'scapula', 'spine'),
  L('coracoid_process', "Coracoid process", 'scapula', 'process'),
  L('supraglenoid_tubercle', "Supraglenoid tubercle", 'scapula', 'tubercle'),
  L('infraglenoid_tubercle', "Infraglenoid tubercle", 'scapula', 'tubercle'),
  L('supraspinous_fossa', "Supraspinous fossa", 'scapula', 'fossa'),
  L('infraspinous_fossa', "Infraspinous fossa", 'scapula', 'fossa'),
  L('subscapular_fossa', "Subscapular fossa", 'scapula', 'fossa'),
  L('scapula_medial_border', "Medial border of the scapula", 'scapula', 'border'),
  L('scapula_lateral_border', "Lateral border of the scapula", 'scapula', 'border'),
  L('scapula_inferior_angle', "Inferior angle of the scapula", 'scapula', 'angle'),
  L('scapula_superior_angle', "Superior angle of the scapula", 'scapula', 'angle'),
  L('greater_tubercle', "Greater tubercle of the humerus", 'humerus', 'tubercle'),
  L('lesser_tubercle', "Lesser tubercle of the humerus", 'humerus', 'tubercle'),
  L('intertubercular_groove_lateral', "Lateral lip of the intertubercular groove", 'humerus', 'groove'),
  L('intertubercular_groove_medial', "Medial lip of the intertubercular groove", 'humerus', 'groove'),
  L('intertubercular_groove_floor', "Floor of the intertubercular groove", 'humerus', 'groove'),
  L('deltoid_tuberosity', "Deltoid tuberosity", 'humerus', 'tuberosity'),
  L('humerus_shaft_medial', "Medial humeral shaft", 'humerus', 'shaft'),
  L('humerus_shaft_posterior', "Posterior humeral shaft", 'humerus', 'shaft'),
  L('medial_epicondyle', "Medial epicondyle of the humerus", 'humerus', 'epicondyle'),
  L('lateral_epicondyle', "Lateral epicondyle of the humerus", 'humerus', 'epicondyle'),
  L('lateral_supracondylar_ridge', "Lateral supracondylar ridge", 'humerus', 'ridge'),
  L('radial_tuberosity', "Radial tuberosity", 'radius', 'tuberosity'),
  L('radius_shaft', "Shaft of the radius", 'radius', 'shaft'),
  L('radius_styloid', "Styloid process of the radius", 'radius', 'process'),
  L('olecranon', "Olecranon", 'ulna', 'region'),
  L('ulna_shaft', "Shaft of the ulna", 'ulna', 'shaft'),
  L('ulna_coronoid', "Coronoid process of the ulna", 'ulna', 'process'),
  L('pisiform', "Pisiform", 'pisiform', 'region'),
  L('metacarpal_2_3_base', "Base of the 2nd and 3rd metacarpals", 'metacarpal', 'region'),
  L('metacarpal_5_base', "Base of the 5th metacarpal", 'metacarpal', 'region'),
  L('metacarpal_1_base', "Base of the 1st metacarpal", 'metacarpal', 'region'),
  L('phalanges_middle', "Middle phalanges", 'phalanx_hand', 'region'),
  L('phalanges_distal_hand', "Distal phalanges", 'phalanx_hand', 'region'),
  L('extensor_expansion', "Extensor expansion", undefined, 'region'),
  L('iliac_crest', "Iliac crest", 'hip_bone', 'crest'),
  L('asis', "Anterior superior iliac spine (ASIS)", 'hip_bone', 'spine'),
  L('aiis', "Anterior inferior iliac spine (AIIS)", 'hip_bone', 'spine'),
  L('iliac_fossa', "Iliac fossa", 'hip_bone', 'fossa'),
  L('gluteal_surface', "Gluteal surface of the ilium", 'hip_bone', 'surface'),
  L('psis', "Posterior superior iliac spine (PSIS)", 'hip_bone', 'spine'),
  L('ischial_tuberosity', "Ischial tuberosity", 'hip_bone', 'tuberosity'),
  L('ischial_ramus', "Ischial ramus", 'hip_bone', 'region'),
  L('ischial_spine', "Ischial spine", 'hip_bone', 'spine'),
  L('pubic_body', "Body of the pubis", 'hip_bone', 'region'),
  L('pubic_ramus_inferior', "Inferior pubic ramus", 'hip_bone', 'region'),
  L('pubic_ramus_superior', "Superior pubic ramus", 'hip_bone', 'region'),
  L('pubic_tubercle', "Pubic tubercle", 'hip_bone', 'tubercle'),
  L('pectineal_line_pubis', "Pectineal line of the pubis", 'hip_bone', 'line'),
  L('obturator_foramen', "Margin of the obturator foramen", 'hip_bone', 'foramen'),
  L('greater_trochanter', "Greater trochanter", 'femur', 'trochanter'),
  L('lesser_trochanter', "Lesser trochanter", 'femur', 'trochanter'),
  L('gluteal_tuberosity', "Gluteal tuberosity", 'femur', 'tuberosity'),
  L('linea_aspera', "Linea aspera", 'femur', 'line'),
  L('femur_shaft_anterior', "Anterior femoral shaft", 'femur', 'shaft'),
  L('intertrochanteric_crest', "Intertrochanteric crest", 'femur', 'trochanter'),
  L('femur_condyle_medial', "Medial femoral condyle", 'femur', 'condyle'),
  L('femur_condyle_lateral', "Lateral femoral condyle", 'femur', 'condyle'),
  L('adductor_tubercle', "Adductor tubercle", 'femur', 'tubercle'),
  L('patella_base', "Base of the patella", 'patella', 'region'),
  L('tibial_tuberosity', "Tibial tuberosity", 'tibia', 'tuberosity'),
  L('pes_anserinus', "Pes anserinus (medial tibia)", undefined, 'region'),
  L('tibia_lateral_condyle', "Lateral condyle of the tibia", 'tibia', 'condyle'),
  L('tibia_medial_condyle', "Medial condyle of the tibia", 'tibia', 'condyle'),
  L('tibia_shaft_lateral', "Lateral tibial shaft", 'tibia', 'shaft'),
  L('tibia_shaft_posterior', "Posterior tibial shaft", 'tibia', 'shaft'),
  L('soleal_line', "Soleal line of the tibia", 'tibia', 'line'),
  L('fibula_head', "Head of the fibula", 'fibula', 'head'),
  L('fibula_shaft_lateral', "Lateral fibular shaft", 'fibula', 'shaft'),
  L('fibula_shaft_posterior', "Posterior fibular shaft", 'fibula', 'shaft'),
  L('interosseous_membrane_leg', "Interosseous membrane (leg)", undefined, 'membrane'),
  L('calcaneus', "Calcaneus", 'calcaneus', 'region'),
  L('calcaneal_tendon', "Calcaneal (Achilles) tendon", undefined, 'aponeurosis'),
  L('navicular', "Navicular", 'navicular', 'region'),
  L('medial_cuneiform', "Medial cuneiform", 'cuneiform', 'region'),
  L('metatarsal_1_base', "Base of the 1st metatarsal", 'metatarsal', 'region'),
  L('metatarsal_5_base', "Base of the 5th metatarsal", 'metatarsal', 'region'),
  L('phalanges_distal_foot', "Distal phalanges (foot)", 'phalanx_foot', 'region'),
  L('hallux_distal', "Distal phalanx of the hallux", 'phalanx_foot', 'region'),
  L('iliotibial_band', "Iliotibial band", undefined, 'fascia'),
  L('humerus_shaft_anterior', "Anterior distal humeral shaft", 'humerus', 'shaft'),
  L('supinator_crest', "Supinator crest of the ulna", 'ulna', 'crest'),
  L('hamate', "Hamate", 'hamate', 'region'),
  L('palmar_aponeurosis', "Palmar aponeurosis", undefined, 'aponeurosis'),
  L('interosseous_membrane_forearm', "Interosseous membrane (forearm)", undefined, 'membrane'),
  L('external_oblique_aponeurosis', "Aponeurosis of external oblique", undefined, 'aponeurosis'),
  L('linea_alba', "Linea alba", undefined, 'line'),
  L('inguinal_ligament', "Inguinal ligament", undefined, 'ligament'),
  L('pubic_crest', "Pubic crest", 'hip_bone', 'crest'),
  L('iliac_crest_inner', "Inner lip of the iliac crest", 'hip_bone', 'crest'),
  L('sacrotuberous_ligament', "Sacrotuberous ligament", undefined, 'ligament'),
  L('anterior_sacroiliac', "Anterior sacrum and sacroiliac region", 'sacrum', 'region'),
  L('t1_t6_transverse', "Transverse processes of T1–T6", 'thoracic_vertebra', 'process'),
  L('c4_c6_transverse', "Transverse processes of C4–C6", 'cervical_vertebra', 'process'),
  L('c2_c4_spinous', "Spinous processes of C2–C4 / ligamentum nuchae", 'cervical_vertebra', 'ligament'),
  L('t3_t6_spinous', "Spinous processes of T3–T6", 'thoracic_vertebra', 'process'),
  L('ribs_lower_inner', "Inner surface of the lower ribs", 'rib', 'surface'),
  L('rib_12', "Twelfth rib", 'rib', 'region'),
  L('iliolumbar_ligament', "Iliolumbar ligament", undefined, 'ligament'),
  L('sacrum_iliac_common', "Common tendon: sacrum, iliac crest, lumbar spinous processes", 'sacrum', 'aponeurosis'),
  L('pectineal_line_femur', "Pectineal line of the femur", 'femur', 'line'),
  L('trochanteric_fossa', "Trochanteric fossa", 'femur', 'trochanter'),
  L('lateral_supracondylar_line', "Lateral supracondylar line of the femur", 'femur', 'line'),
  L('intertrochanteric_line', "Intertrochanteric line", 'femur', 'trochanter'),
  L('acetabulum', "Acetabulum", 'hip_bone', 'region'),
  L('obturator_membrane', "Obturator membrane", undefined, 'membrane'),
  L('cuneiforms', "Cuneiform bones", 'cuneiform', 'region'),
  L('metatarsals_2_4_base', "Bases of the 2nd–4th metatarsals", 'metatarsal', 'region'),
  L('phalanges_middle_foot', "Middle phalanges (foot)", 'phalanx_foot', 'region'),
  L('fibula_neck', "Neck of the fibula", 'fibula', 'neck'),
  L('ribs_5_12_outer', "Outer surface of ribs 5–12", 'rib', 'surface'),
  L('ribs_10_12', "Ribs 10–12", 'rib', 'region'),
  L('costal_cartilages_5_7', "Costal cartilages 5–7", undefined, 'region'),
  L('rib_2', "Second rib", 'rib', 'region'),
  L('occipital_between_nuchal_lines', "Occipital bone between the nuchal lines", 'occipital', 'region'),
  L('cervical_transverse_all', "Cervical transverse processes", 'cervical_vertebra', 'process'),
  L('c1_c3_transverse', "Transverse processes of C1–C3", 'cervical_vertebra', 'process'),
  L('c7_t6_transverse', "Transverse processes of C7–T6", 'thoracic_vertebra', 'process'),
  L('thoracic_transverse', "Thoracic transverse processes", 'thoracic_vertebra', 'process'),
  L('spinous_processes_general', "Spinous processes (two to four levels above)", 'thoracic_vertebra', 'process'),
  L('t12_l5_bodies', "Bodies and discs of T12–L5", 'lumbar_vertebra', 'region'),
  L('pubic_symphysis', "Pubic symphysis", undefined, 'region'),
  L('zygomatic_arch', 'Zygomatic arch', 'zygomatic', 'process'),
  L('temporal_fossa', 'Temporal fossa', 'temporal', 'fossa'),
  L('mandible_coronoid', 'Coronoid process of the mandible', 'mandible', 'process'),
  L('mandible_ramus', 'Ramus of the mandible', 'mandible', 'surface'),
  L('mandible_angle', 'Angle of the mandible', 'mandible', 'angle'),
  L('mandible_condyle', 'Condylar neck of the mandible', 'mandible', 'neck'),
  L('mylohyoid_line', 'Mylohyoid line of the mandible', 'mandible', 'line'),
  L('digastric_fossa', 'Digastric fossa of the mandible', 'mandible', 'fossa'),
  L('mental_spine', 'Inferior mental spine of the mandible', 'mandible', 'spine'),
  L('mandible_body', 'Body of the mandible', 'mandible', 'surface'),
  L('lateral_pterygoid_plate', 'Lateral pterygoid plate', 'sphenoid', 'process'),
  L('sphenoid_greater_wing', 'Greater wing of the sphenoid', 'sphenoid', 'surface'),
  L('common_tendinous_ring', 'Common tendinous ring', 'sphenoid', 'region'),
  L('styloid_process_temporal', 'Styloid process of the temporal bone', 'temporal', 'process'),
  L('mastoid_notch', 'Mastoid notch', 'temporal', 'notch'),
  L('nuchal_line_inferior', 'Inferior nuchal line', 'occipital', 'line'),
  L('basilar_occipital', 'Basilar part of the occipital bone', 'occipital', 'surface'),
  L('atlas_anterior_tubercle', 'Anterior tubercle of the atlas', 'atlas', 'tubercle'),
  L('atlas_posterior_tubercle', 'Posterior tubercle of the atlas', 'atlas', 'tubercle'),
  L('atlas_transverse', 'Transverse process of the atlas', 'atlas', 'process'),
  L('atlas_lateral_mass', 'Lateral mass of the atlas', 'atlas', 'surface'),
  L('axis_spinous', 'Spinous process of the axis', 'axis', 'spine'),
  L('sclera', 'Sclera of the eyeball', undefined, 'surface'),
  L('tarsal_plate', 'Superior tarsal plate of the eyelid', undefined, 'region'),
  L('facial_skin', 'Skin and superficial fascia of the face', undefined, 'fascia'),
  L('galea_aponeurotica', 'Galea aponeurotica', undefined, 'aponeurosis'),
  L('medial_palpebral_ligament', 'Medial palpebral ligament', undefined, 'ligament'),
  L('pterygomandibular_raphe', 'Pterygomandibular raphe', undefined, 'ligament'),
  L('maxilla_alveolar', 'Alveolar process of the maxilla', 'maxilla', 'process'),
  L('mandible_alveolar', 'Alveolar process of the mandible', 'mandible', 'process'),
  L('hyoid_body', 'Body of the hyoid', 'hyoid', 'surface'),
  L('hyoid_greater_horn', 'Greater horn of the hyoid', 'hyoid', 'process'),
  L('thyroid_cartilage', 'Oblique line of the thyroid cartilage', undefined, 'line'),
  L('cervical_bodies_c3_t3', 'Bodies of C3–T3', 'cervical_vertebra', 'surface'),
  L('c3_c6_transverse', 'Transverse processes of C3–C6', 'cervical_vertebra', 'process'),
  // hand
  L('flexor_retinaculum', 'Flexor retinaculum of the wrist', undefined, 'ligament'),
  L('scaphoid_tubercle', 'Tubercle of the scaphoid', 'scaphoid', 'tubercle'),
  L('trapezium_tubercle', 'Tubercle of the trapezium', 'trapezium', 'tubercle'),
  L('hamate_hook', 'Hook of the hamate', 'hamate', 'process'),
  L('capitate_body', 'Body of the capitate', 'capitate', 'surface'),
  L('metacarpal_shafts', 'Shafts of the metacarpals', 'metacarpal', 'shaft'),
  L('metacarpal_1_shaft', 'Shaft of the 1st metacarpal', 'metacarpal', 'shaft'),
  L('metacarpal_5_shaft', 'Shaft of the 5th metacarpal', 'metacarpal', 'shaft'),
  L('phalanges_proximal_hand', 'Proximal phalanges (hand)', 'phalanx_hand', 'surface'),
  L('thumb_proximal_phalanx', 'Proximal phalanx of the thumb', 'phalanx_hand', 'surface'),
  L('thumb_distal_phalanx', 'Distal phalanx of the thumb', 'phalanx_hand', 'surface'),
  L('fdp_tendons', 'Tendons of flexor digitorum profundus', undefined, 'aponeurosis'),
  L('palmar_skin', 'Skin of the medial palm', undefined, 'fascia'),
  // foot
  L('calcaneal_tuberosity', 'Tuberosity of the calcaneus', 'calcaneus', 'tuberosity'),
  L('calcaneus_dorsal', 'Dorsal surface of the calcaneus', 'calcaneus', 'surface'),
  L('plantar_aponeurosis', 'Plantar aponeurosis', undefined, 'aponeurosis'),
  L('lateral_cuneiform', 'Lateral cuneiform', 'cuneiform', 'surface'),
  L('cuboid_plantar', 'Plantar surface of the cuboid', 'cuboid', 'surface'),
  L('metatarsal_shafts', 'Shafts of the metatarsals', 'metatarsal', 'shaft'),
  L('metatarsal_5_shaft', 'Shaft of the 5th metatarsal', 'metatarsal', 'shaft'),
  L('phalanges_proximal_foot', 'Proximal phalanges (foot)', 'phalanx_foot', 'surface'),
  L('hallux_proximal', 'Proximal phalanx of the hallux', 'phalanx_foot', 'surface'),
  L('fdl_tendon', 'Tendon of flexor digitorum longus', undefined, 'aponeurosis'),
  L('extensor_expansion_foot', 'Extensor expansions (foot)', undefined, 'aponeurosis'),
  L('plantar_mtp_ligaments', 'Plantar metatarsophalangeal ligaments', undefined, 'ligament'),
  // trunk
  L('central_tendon', 'Central tendon of the diaphragm', undefined, 'aponeurosis'),
  L('costal_margin', 'Costal margin (ribs 7–12)', 'rib', 'border'),
  L('l1_l3_bodies', 'Bodies of L1–L3', 'lumbar_vertebra', 'surface'),
  L('rib_borders', 'Upper and lower borders of adjacent ribs', 'rib', 'border'),
  L('rib_inner', 'Inner surface of the ribs', 'rib', 'surface'),
  L('scapula_superior_border', 'Superior border of the scapula', 'scapula', 'border'),
  L('transverse_processes_general', 'Transverse processes (one to two levels below)',
    'thoracic_vertebra', 'process'),
  L('spinous_adjacent', 'Adjacent spinous processes', 'thoracic_vertebra', 'spine'),
  L('transverse_adjacent', 'Adjacent transverse processes', 'thoracic_vertebra', 'process'),
  L('perineal_body', 'Perineal body', undefined, 'region'),
  L('anococcygeal_ligament', 'Anococcygeal ligament', undefined, 'ligament'),
  L('pubis_inner', 'Inner surface of the body of the pubis', 'hip_bone', 'surface'),
  L('tendinous_arch_levator', 'Tendinous arch of the levator ani', undefined, 'fascia'),
  L('manubrium_posterior', 'Posterior surface of the manubrium', 'sternum', 'surface'),
]

export const JOINTS: Joint[] = [
  { id: 'glenohumeral', name: 'Glenohumeral (shoulder)', type: 'ball_and_socket',
    boneIds: ['scapula', 'humerus'],
    actions: ['flexion', 'extension', 'abduction', 'adduction', 'internal_rotation',
              'external_rotation', 'horizontal_adduction', 'horizontal_abduction', 'circumduction'] },
  { id: 'scapulothoracic', name: 'Scapulothoracic', type: 'plane',
    boneIds: ['scapula', 'rib'],
    actions: ['elevation', 'depression', 'protraction', 'retraction',
              'upward_rotation', 'downward_rotation'] },
  { id: 'elbow', name: 'Elbow', type: 'hinge',
    boneIds: ['humerus', 'ulna', 'radius'], actions: ['flexion', 'extension'] },
  { id: 'radioulnar', name: 'Radioulnar', type: 'pivot',
    boneIds: ['radius', 'ulna'], actions: ['pronation', 'supination'] },
  { id: 'wrist', name: 'Wrist', type: 'condyloid',
    boneIds: ['radius', 'scaphoid', 'lunate'],
    actions: ['flexion', 'extension', 'abduction', 'adduction'] },
  { id: 'fingers', name: 'Finger joints', type: 'hinge',
    boneIds: ['metacarpal', 'phalanx_hand'],
    actions: ['flexion', 'extension', 'abduction', 'adduction', 'opposition'] },
  { id: 'hip', name: 'Hip', type: 'ball_and_socket',
    boneIds: ['hip_bone', 'femur'],
    actions: ['flexion', 'extension', 'abduction', 'adduction',
              'internal_rotation', 'external_rotation', 'circumduction'] },
  { id: 'knee', name: 'Knee', type: 'hinge',
    boneIds: ['femur', 'tibia', 'patella'],
    actions: ['flexion', 'extension', 'internal_rotation', 'external_rotation'] },
  { id: 'ankle', name: 'Talocrural (ankle)', type: 'hinge',
    boneIds: ['tibia', 'fibula', 'talus'], actions: ['dorsiflexion', 'plantarflexion'] },
  { id: 'subtalar', name: 'Subtalar', type: 'plane',
    boneIds: ['talus', 'calcaneus'], actions: ['inversion', 'eversion'] },
  { id: 'toes', name: 'Toe joints', type: 'hinge',
    boneIds: ['metatarsal', 'phalanx_foot'],
    actions: ['flexion', 'extension', 'abduction', 'adduction'] },
  { id: 'spine', name: 'Vertebral column', type: 'cartilaginous',
    boneIds: ['cervical_vertebra', 'thoracic_vertebra', 'lumbar_vertebra'],
    actions: ['flexion', 'extension', 'lateral_flexion', 'rotation'] },
  { id: 'cervical_spine_joint', name: 'Cervical spine', type: 'cartilaginous',
    boneIds: ['occipital', 'cervical_vertebra'],
    actions: ['flexion', 'extension', 'lateral_flexion', 'rotation'] },
  { id: 'temporomandibular', name: 'Temporomandibular joint', type: 'condyloid',
    boneIds: ['temporal', 'mandible'],
    actions: ['elevation', 'depression', 'protraction', 'retraction', 'rotation'] },
  { id: 'atlanto_occipital', name: 'Atlanto-occipital joint', type: 'condyloid',
    boneIds: ['occipital', 'atlas'], actions: ['flexion', 'extension', 'lateral_flexion'] },
  { id: 'atlanto_axial', name: 'Atlanto-axial joint', type: 'pivot',
    boneIds: ['atlas', 'axis'], actions: ['rotation'] },
  { id: 'thumb_cmc', name: 'Carpometacarpal joint of the thumb', type: 'saddle',
    boneIds: ['trapezium', 'metacarpal'],
    actions: ['flexion', 'extension', 'abduction', 'adduction', 'opposition', 'circumduction'] },
  { id: 'costovertebral', name: 'Costovertebral and costal joints', type: 'plane',
    boneIds: ['rib', 'thoracic_vertebra', 'sternum'], actions: ['elevation', 'depression'] },
  { id: 'eye', name: 'Eyeball (orbital movement)', type: 'ball_and_socket',
    boneIds: ['sphenoid'],
    actions: ['elevation', 'depression', 'abduction', 'adduction',
              'internal_rotation', 'external_rotation'] },
]
